### ISSUE TITLE
Unable to connect to a dragonfly memcache instance

### ISSUE THREAD

**Issue by rocktavious** [petergoldstein/dalli#1003]
Hello,

We are looking at using this client library with a [dragonfly cluster via its memcache](https://www.dragonflydb.io/docs/managing-dragonfly/memcached-mode) support and seem to be running into an error with client initializiation.

```
irb(main):013> require "dalli"
=> false
irb(main):014> dc = Dalli::Client.new("memcache.staging.svc.cluster.local:11211")
=> #<Dalli::Client:0x00007f1cb51ef108 @key_manager=#<Dalli::KeyManager:0x00007f1cc0335b88 @key_options={:digest_class=>Digest::MD5}, @namespace=nil>, @normalized_servers=["memcache.staging.svc.cluster.local:11211"], @options={}, @ring=nil>
irb(main):015> dc.set('abc', 123)
W, [2024-05-21T18:44:13.310039 #96]  WARN -- : memcache.staging.svc.cluster.local:11211 failed (count: 0) Timeout::Error: IO timeout: {:host=>"memcache.staging.svc.cluster.local", :port=>11211, :down_retry_delay=>30, :socket_timeout=>1, :socket_max_failures=>2, :socket_failure_delay=>0.1, :keepalive=>true}
(irb):15:in `<main>': No server available (Dalli::RingError)
```

I have ruled out dns issues using
```
irb(main):001> require 'resolv'
=> false
irb(main):002> Resolv.getname "10.100.251.152"
=> "memcache.staging.svc.cluster.local"
irb(main):009> Resolv.getaddress "memcache.staging.svc.cluster.local"
=> "10.100.251.152"
```

The configuration of the dragonfly cluster is straight forward
```
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  labels:
    app.kubernetes.io/name: dragonfly-memcache
    app.kubernetes.io/instance: dragonfly-opslevel
    app.kubernetes.io/managed-by: kustomize
  name: memcache
  namespace: staging
spec:
  priorityClassName: critical-priority
  replicas: 1
  memcachedPort: 11211
  resources:
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      cpu: 600m
      memory: 3Gi
```

I'm trying to understand if this is a bug to report to the dragonfly maintainers or if there is something the dalli maintainers are doing incorrect with initialization.

Any help would be appreciated.

**Comment by petergoldstein** [comment]
@rocktavious I don't think I can be of much help here.  Dalli is a memcached client, intended for use with memcached.  Dragonfly may expose an interface that claims a degree of memcached compatiblity, but it's hard to assess how good that compatibility is given the information they provide (as an example, what version of memcached do they claim to be compatible with?  Which protocol(s)? - none of this is specified in the documentation).  Dalli initialization works just fine with memcached.

I would suggest you speak with the Dragonfly support team to better understand the level and nature of compatibility they offer at the protocol level, which will better help you understand your options.

**Comment by rocktavious** [comment]
Thanks for your input @petergoldstein.
