### ISSUE TITLE
Response error 133/132

### ISSUE THREAD

**Issue by pcboy** [petergoldstein/dalli#117]
Hi,

Dalli is throwing me some errors on some Gets.

(Dalli::DalliError) "Response error 133 "
(Dalli::DalliError) "Response error 132 "

 dalli (1.1.1) lib/dalli/server.rb:326:in `generic_response'
 dalli (1.1.1) lib/dalli/server.rb:146:in`get'
 dalli (1.1.1) lib/dalli/server.rb:46:in `send'
 dalli (1.1.1) lib/dalli/server.rb:46:in`request'
 dalli (1.1.1) lib/dalli/options.rb:18:in `request'
 /usr/local/lib/ruby/1.8/monitor.rb:242:in`synchronize'
 dalli (1.1.1) lib/dalli/options.rb:17:in `request'
 dalli (1.1.1) lib/dalli/client.rb:252:in`perform'
 dalli (1.1.1) lib/dalli/client.rb:61:in `get'

It's happening randomly and I couldn't find anything on the web. What's the problem?

Thanks.

**Comment by dentarg** [comment]
I got this error with dalli 2.7.4, using [memcachier.com](https://www.memcachier.com/) (the dalli client reports version 1.4.20 for the server).

```
Dalli::DalliError: Response error 133: 
  from /app/lib/pinger_thread.rb:16:in `block in start'
  from raven/base.rb:104:in `capture'
  from /app/lib/pinger_thread.rb:33:in `block (2 levels) in start'
  from /app/lib/pinger_thread.rb:33:in `loop'
  from /app/lib/pinger_thread.rb:46:in `block (3 levels) in start'
  from twingly/amqp/pinger.rb:25:in `ping'
  from twingly/amqp/pinger.rb:25:in `each'
  from twingly/amqp/pinger.rb:26:in `block in ping'
  from twingly/amqp/pinger.rb:63:in `cached?'
  from twingly/url_cache.rb:26:in `cached?'
  from retryable.rb:67:in `retryable'
  from twingly/url_cache.rb:27:in `block in cached?'
  from dalli/client.rb:56:in `get'
  from dalli/client.rb:333:in `perform'
  from dalli/options.rb:17:in `request'
  from monitor.rb:211:in `mon_synchronize'
  from dalli/options.rb:18:in `block in request'
  from dalli/server.rb:63:in `request'
  from dalli/server.rb:261:in `get'
  from dalli/server.rb:490:in `generic_response'
```

The response codes in question (132 = 0x84, 133 = 0x85) are documented at https://code.google.com/p/memcached/wiki/BinaryProtocolRevamped#Response_Status

But perhaps dalli doesn't support the revamped protocol?

(I also couldn't find the response codes anywhere at [memcached/memcached](https://github.com/memcached/memcached), but I did find them in [couchbase/memcached](https://github.com/couchbase/memcached/blob/master/include/memcached/protocol_binary.h#L121-L138), yeah I'm a bit confused on what's going on – I can see that many other clients have implemented them: [philopon/memcached-binary](https://github.com/philopon/memcached-binary/blob/42295c38b926b3eaebd49fef9652c1a383cfca9c/src/Database/Memcached/Binary/Types/Exception.hs#L34-L37), [derekwyatt/akka-memcached](https://github.com/derekwyatt/akka-memcached/blob/2930cba15f05df077fa5a451b307625291f6cdab/src/main/scala/com/codeseq/mcdc/client.scala#L41-L44), [couchbase/spymemcached](https://github.com/couchbase/spymemcached/blob/905c13c1d3453d882e80f48d18bdfecdeadc6d24/src/test/java/net/spy/memcached/ErrorCodeTest.java#L53-L56), [dqminh/gocached](https://github.com/dqminh/gocached/blob/0aadb0a8f29278da7f43644d58aa6928a78dd851/constant.go#L51-L54))

**Comment by dterei** [comment]
So you should contact support@memcachier.com about these kinds of issues generally. But just to explain in case others come across this thread when using MemCachier.

MemCachier will occasionally send the error code, `133` or in hex, `0x85`. It indicates a transient internal error on the server side that occurs when a MemCachier cluster cluster is currently doing some reconfiguration and can't service requests temporarily. This type of situation is generally very rare and short-lived.

@mperham sorry if this isn't appropriate (feel free to clean up any way you like), but thought it may help others who find this through google and prevent them starting tickets that aren't to do with dalli.

**Comment by petergoldstein** [comment]
@dterei Thanks for clarifying.  As we only use the response code for the error message, I chose to add these additional codes to Dalli (based on the Google document referenced above).  Hopefully this will result in better error messages for Dalli users who run into this going forward.
