### ISSUE TITLE
Why do we need Rails.cache.reset

### ISSUE THREAD

**Issue by kineticac** [petergoldstein/dalli#128]
Hey Mike / everyone,

if defined?(PhusionPassenger)
  PhusionPassenger.on_event(:starting_worker_process) do |forked|
    # Only works with DalliStore
    Rails.cache.reset if forked
  end
end

Why is this needed at the bottom of environment.rb?  The reason I ask is we're currently getting an error with Rails.cache.reset in our newest instance in EC2 (which is a different place than where we've been running the app).  This is the error:

[ pid=22948 thr=72263830 file=utils.rb:176 time=2011-10-06 23:47:51.679 ]: **\* Exception NoMethodError in application (undefined method `reset' for #ActiveSupport::Cache::MemCacheStore:0x9a1521c) (process 22948, thread #Thread:0x89d512c)

Have you seen this before?  Can we proceed with using DalliStore even if we're on passenger without this line?

**Comment by alex198211** [comment]
Is this still necessary nowadays? I have a Rails 4.2 application behind passenger 5.0.26 on apache 2.4.5. I use ruby 2.3.1 and dalli 2.7.8. I am getting wrong output from the cache. 

Should I do this on fork?
`Rails.cache.reset if Rails.cache.class == ActiveSupport::Cache:DalliStore`
