### ISSUE TITLE
Fallback to actual block if server down

### ISSUE THREAD

**Issue by International** [petergoldstein/dalli#252]
Imagine I have something like this:

``` ruby
Rails.cache.fetch("my_model_1") { MyModel.find(1) }
```

On Heroku, the memcachier server seems to die pretty randomly, and thus, it causes errors ( because of data being nil ). Is it possible to failover to actually perform a block's action if a server's not alive? I'd gladly trade performance to being able to run without such failures.

**Comment by ksheurs** [comment]
Hi there. We are finding `Dalli::RingError` is still raised even with `:raise_errors => false`. Is it possible to include this exception in the ignored exception list?

**Comment by petergoldstein** [comment]
@ksheurs Please open a new issue with your request/concern rather than commenting on a closed, only somewhat related issue from 1.5 years ago.  Thanks.

**Comment by ksheurs** [comment]
will do!
