### ISSUE TITLE
Rack::Cache using dalli_store responses empty assets when memcached is down

### ISSUE THREAD

**Issue by shtoma** [petergoldstein/dalli#322]
When memcached is down, the Rack::Cache responses empty asset files.
The caches directly getting from Rails.cache.fetch block is working well, 
for example,

`class Category < ActiveRecord::Base
  def self.all_cache
    Rails.cache.fetch(Constants::CACHE_KEY_CATEGORY_ALL,:expires_in => 1.days) { all }
  end`

This code works well to get data from DB when memcached is down.

How to configure Rack::Cache not to get data from dalli when memcached is down?
I hope in this case Rack::Cache not working (No cache to response assets) or
another storage using.

_my log_
`Cache read: https://MYLOCALAPP/assets/application-common.css?body=1
down_retry_delay not reached for localhost:11211 (0.171 seconds left)
DalliError: No server available
Started GET "/assets/application-common.css?body=1" for 192.168.179.1 at 2013-01-24 15:34:36 +0900
Served asset /application-common.css - 200 OK (126ms)
Cache write: a08d8ac8db030df981ff87a38b7d4d84bba0f10d
down_retry_delay not reached for localhost:11211 (0.037 seconds left)
DalliError: No server available
Cache read: a08d8ac8db030df981ff87a38b7d4d84bba0f10d
down_retry_delay not reached for localhost:11211 (0.037 seconds left)
DalliError: No server available
Cache read: https://MYLOCALAPP/assets/application-common.css?body=1
down_retry_delay not reached for localhost:11211 (0.035 seconds left)
DalliError: No server available
Cache write: https://MYLOCALAPP/assets/application-common.css?body=1
down_retry_delay not reached for localhost:11211 (0.027 seconds left)
DalliError: No server available`

_my config/environments/{Rails.env}.rb (config.action_dispatch.rack_cache is not set)_
```config.cache_classes = true
config.action_controller.perform_caching = true
  config.cache_store = :dalli_store, 'localhost',
  { :namespace => Rails.application.class.parent_name, :expires_in => 10.minutes, :compress => true }

**Comment by petergoldstein** [comment]
@shtoma Is this still an issue?  And did you determine whether it was a Dalli or Rack::Cache issue?
