### ISSUE TITLE
PHP-JSON compatibility issue

### ISSUE THREAD

**Issue by sandys** [petergoldstein/dalli#333]
I'm unable to access json created from Dalli (either as part of Rails session store or standalone) in any PHP clients, however I can read data created from PHP on Dalli.

Here's my ruby script:

require 'dalli'
require 'json'
dc = Dalli::Client.new('localhost:11211', :compress => false, :serializer => JSON)
dc.set "ruby","{\"a\":{\"111\":222}}"

Here's my PHP script (which returns nothing)
$a = new Memcached();
$a->addServer('127.0.0.1',11211);
//$a->setOption(Memcached::OPT_SERIALIZER, Memcached::SERIALIZER_JSON);
$str3 = $a->get("ruby");
echo "$str3";

if you set data from PHP however, its perfectly accessible from Ruby.
$a->set("sss1", "{\"sss1\":2, \"kk\":{\"pp\":11}}");

Not sure if this is deliberate. I'm using latest versions of everything.

**Comment by etherbob** [comment]
the flag setting still seems like a bug to me
