### ISSUE TITLE
Unable to uncompress value: buffer error

### ISSUE THREAD

**Issue by inspire22** [petergoldstein/dalli#370]
Sometimes after a deploy, dalli comes up with this error for *every* read it does.

I've since set :compress => false, since I'm not storing huge values.  But it was pretty annoying.  Only happened maybe 1/30 deployments, but it would cause a mess

It's not just a particular key - it does this for every key.

Restarting the memcache server solved it (but cleared my cache, which sucks as well).

I'm calling .reset on my dalli object in my unicorn's after_fork, as is necessary with preload_app

Unable to uncompress value: buffer error
Dalli::UnmarshalError
thorn
/u/apps/newap/shared/bundle/ruby/2.0.0/gems/dalli-2.6.3/lib/dalli/server.rb:430:in `rescue in deserialize'
/u/apps/newap/shared/bundle/ruby/2.0.0/gems/dalli-2.6.3/lib/dalli/server.rb:420:in `deserialize'
/u/apps/newap/shared/bundle/ruby/2.0.0/gems/dalli-2.6.3/lib/dalli/server.rb:477:in `generic_response'
/u/apps/newap/shared/bundle/ruby/2.0.0/gems/dalli-2.6.3/lib/dalli/server.rb:252:in `get'
/u/apps/newap/shared/bundle/ruby/2.0.0/gems/dalli-2.6.3/lib/dalli/server.rb:56:in `request'
/u/apps/newap/shared/bundle/ruby/2.0.0/gems/dalli-2.6.3/lib/dalli/options.rb:18:in `block in request'
/usr/local/rvm/rubies/ruby-2.0.0-p195/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/u/apps/newap/shared/bundle/ruby/2.0.0/gems/dalli-2.6.3/lib/dalli/options.rb:17:in `request'
/u/apps/newap/shared/bundle/ruby/2.0.0/gems/dalli-2.6.3/lib/dalli/client.rb:329:in `perform'
/u/apps/newap/shared/bundle/ruby/2.0.0/gems/dalli-2.6.3/lib/dalli/client.rb:62:in `get'
(eval):7:in `block in get_with_newrelic_trace'
/u/apps/newap/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.6.2.96/lib/new_relic/agent/method_tracer.rb:273:in `trace_execution_scoped'
(eval):4:in `get_with_newrelic_trace'
/u/apps/newap/current/lib/extend.rb:751:in `[]'
/u/apps/newap/current/app/controllers/app_filters.rb:404:in `count_guest'

**Comment by petergoldstein** [comment]
This is an old issue that never got much attention.  The nature of the issue also isn't entirely clear.  Closing.

@inspire22 , please reopen if this is still an issue for you with a 2.7.x version of Dalli.
