### ISSUE TITLE
Storing 600 objects in Dalli::Ring causes problems with rails request.inspect

### ISSUE THREAD

**Issue by inspire22** [petergoldstein/dalli#371]
As is common when saving errors to the database, I store request.inspect.  

Since there are so many ring objects in there, it takes like 800k/error - when the app has an issue, this can cause a snowball effect as the slave gets backed up trying to sync all those rows, which causes more problems, etc.

Any tips on how to inspect request without showing the massive ring?

I'm also dealing with some memory-bloat problems, which makes me really suspicious of all those entries, though you've said it's normal so I'm trying to ignore it :)

Thanks for a great project.

https://github.com/mperham/dalli/issues/288

**Comment by petergoldstein** [comment]
Calling request.inspect and persisting to the database isn't something I'd recommend.  There's no indication of an actual memory problem outside of the inspect, so closing
