### ISSUE TITLE
NameError raised when deserialising data from another app that contains it's own objects/classes

### ISSUE THREAD

**Issue by seawolf** [petergoldstein/dalli#374]
_Class names have been changed to protect the innocent._
- - -

### Background

I've a Rails 3.1 site that exposes a JSON API and a Rails 4.0-beta1 site for the client.

The service has the following classes:
-  Person < ActiveRecord::Base
-  Address < ActiveRecord::Base, note that it is not Person::Address. 
-  PersonDecorator

The client has the following classes:
-  Person < ActiveResource::Base
-  PersonSearch

My client queries the API though the PersonSearch wrapper and there it uses Dalli to cache responses. The whole Person object is cached outright, and when de-serialised I can do things like `Person.address.line_1` -- I don't have to reinitialise a Person object in the client from the received data; it all just works and I'm really pleased that!

### Problem

The interesting part comes when:
-  I do a search from the client
-  the results get stored in the cache
-  I restart the client's console/worker/webrick etc.
-  I initiate another search, which hits the cache and returns the expected results without querying the server

During the last step when the data is de-serialised from the cache, the following is shown despite the data being retrieved / parsed / usable:

    2.0.0p0 :001 > ps = PersonSearch.new(123)

    Cache exist: person-123
    Dalli::Server#connect 127.0.0.1:11211
    Unexpected exception in Dalli: NameError: uninitialized constant Person::Address
    This is a bug in Dalli, please enter an issue in Github if it does not already exist.
      /home/seawolf/.rvm/gems/ruby-2.0.0-p0@my_api_client/gems/activesupport-4.0.0.beta1/lib/active_support/inflector/methods.rb:228:in `const_get'
    	/home/seawolf/.rvm/gems/ruby-2.0.0-p0@my_api_client/gems/activesupport-4.0.0.beta1/lib/active_support/inflector/methods.rb:228:in `block in constantize'
    	/home/seawolf/.rvm/gems/ruby-2.0.0-p0@my_api_client/gems/activesupport-4.0.0.beta1/lib/active_support/inflector/methods.rb:224:in `each'
    	/home/seawolf/.rvm/gems/ruby-2.0.0-p0@my_api_client/gems/activesupport-4.0.0.beta1/lib/active_support/inflector/methods.rb:224:in `inject'
    	/home/seawolf/.rvm/gems/ruby-2.0.0-p0@my_api_client/gems/activesupport-4.0.0.beta1/lib/active_support/inflector/methods.rb:224:in `constantize'
    	/home/seawolf/.rvm/gems/ruby-2.0.0-p0@my_api_client/gems/activesupport-4.0.0.beta1/lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
    	/home/seawolf/.rvm/gems/ruby-2.0.0-p0@my_api_client/gems/activesupport-4.0.0.beta1/lib/active_support/core_ext/marshal.rb:8:in `rescue in load_with_autoloading'
    	/home/seawolf/.rvm/gems/ruby-2.0.0-p0@my_api_client/gems/activesupport-4.0.0.beta1/lib/active_support/core_ext/marshal.rb:4:in `load_with_autoloading'
    	/home/seawolf/.rvm/gems/ruby-2.0.0-p0@my_api_client/gems/dalli-2.6.4/lib/dalli/server.rb:423:in `deserialize'
    	/home/seawolf/.rvm/gems/ruby-2.0.0-p0@my_api_client/gems/dalli-2.6.4/lib/dalli/server.rb:479:in `generic_response'
    	/home/seawolf/.rvm/gems/ruby-2.0.0-p0@my_api_client/gems/dalli-2.6.4/lib/dalli/server.rb:256:in `get'
    	/home/seawolf/.rvm/gems/ruby-2.0.0-p0@my_api_client/gems/dalli-2.6.4/lib/dalli/server.rb:60:in `request'
    	/home/seawolf/.rvm/gems/ruby-2.0.0-p0@my_api_client/gems/dalli-2.6.4/lib/dalli/options.rb:18:in `block in request'
    	/home/seawolf/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
    	/home/seawolf/.rvm/gems/ruby-2.0.0-p0@my_api_client/gems/dalli-2.6.4/lib/dalli/options.rb:17:in `request'
    	/home/seawolf/.rvm/gems/ruby-2.0.0-p0@my_api_client/gems/dalli-2.6.4/lib/dalli/client.rb:348:in `perform'
    	/home/seawolf/.rvm/gems/ruby-2.0.0-p0@my_api_client/gems/dalli-2.6.4/lib/dalli/client.rb:62:in `get'
    	(eval):7:in `block in get_with_newrelic_trace'
    	/home/seawolf/.rvm/gems/ruby-2.0.0-p0@my_api_client/gems/newrelic_rpm-3.6.1.88/lib/new_relic/agent/method_tracer.rb:273:in `trace_execution_scoped'
    	(eval):4:in `get_with_newrelic_trace'
    	/home/seawolf/.rvm/gems/ruby-2.0.0-p0@my_api_client/gems/dalli-2.6.4/lib/active_support/cache/dalli_store.rb:229:in `read_entry'
    	/home/seawolf/.rvm/gems/ruby-2.0.0-p0@my_api_client/gems/activesupport-4.0.0.beta1/lib/active_support/cache/strategy/local_cache.rb:129:in `read_entry'
    	/home/seawolf/.rvm/gems/ruby-2.0.0-p0@my_api_client/gems/dalli-2.6.4/lib/active_support/cache/dalli_store.rb:115:in `exist?'

---%<--- (Ruby, Unicorn stuff) ---%<---

    127.0.0.1:11211 is down
    #<Dalli::NetworkError: 127.0.0.1:11211 is down: NameError uninitialized constant Person::Address>
    retrying request with new server
    down_retry_delay not reached for 127.0.0.1:11211 (1.000 seconds left)
    DalliError: No server available
    Cache delete: person-123
    Dalli::Server#connect 127.0.0.1:11211
    127.0.0.1:11211 is back (downtime was 3.718 seconds)
    Cache write: person-123

### Solution

This problem is alleviated by creating a skeletal Address class in the client, which has the same attr_readers and sets them in a tiny #initialize method. I'm trying to do as little as possible to make it stop complaining.

### Notes

While I'm sure this isn't a bug, I noticed that the de-serialised Address object responds to things like #line_1, and Person.address.line_1, that are defined in the server's class definition! It helped me put the above in more of a perspective.

Please feel free to change the issue title, ask for any more information or things you'd like me to try out. While nothing is truly broken, I thought you may want to include some permissive handling of this edge case.

**Comment by petergoldstein** [comment]
This is a classic serialization issue with these sorts of distributed systems, and goes well beyond the scope of Dalli (which is being used as infrastructure in this case).  Closing.
