### ISSUE TITLE
Using dalli_store as Rails session_store

### ISSUE THREAD

**Issue by alikhajeh1** [petergoldstein/dalli#376]
I've followed the readme instructions to do this but get the following exception, any ideas?

require 'action_dispatch/middleware/session/dalli_store'
Rails.application.config.session_store :dalli_store, 
  :memcache_server => ['localhost:11211'], 
  :namespace => 'sessions',
  :key => '_foundation_session',
  :expire_after => 20.minutes

$ bundle exec rails s
Memcached Servers Status
  localhost:11211 - Running
=> Booting Thin
=> Rails 3.2.12 application starting in development on http://0.0.0.0:3000
=> Call with -d to detach
=> Ctrl-C to shutdown server
Exiting
/Users/ali/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/actionpack-3.2.12/lib/action_dispatch/middleware/stack.rb:120:in `assert_index': No such middleware to insert before: ActionDispatch::Session::CookieStore (RuntimeError)
    from /Users/ali/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/actionpack-3.2.12/lib/action_dispatch/middleware/stack.rb:83:in`insert'
    from /Users/ali/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/railties-3.2.12/lib/rails/configuration.rb:38:in `block in merge_into'
    from /Users/ali/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/railties-3.2.12/lib/rails/configuration.rb:37:in`each'
    from /Users/ali/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/railties-3.2.12/lib/rails/configuration.rb:37:in `merge_into'
    from /Users/ali/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/railties-3.2.12/lib/rails/engine.rb:469:in`app'
    from /Users/ali/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/railties-3.2.12/lib/rails/application/finisher.rb:31:in `block in <module:Finisher>'
    from /Users/ali/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/railties-3.2.12/lib/rails/initializable.rb:30:in`instance_exec'
    from /Users/ali/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/railties-3.2.12/lib/rails/initializable.rb:30:in `run'
    from /Users/ali/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/railties-3.2.12/lib/rails/initializable.rb:55:in`block in run_initializers'
    from /Users/ali/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/railties-3.2.12/lib/rails/initializable.rb:54:in `each'
    from /Users/ali/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/railties-3.2.12/lib/rails/initializable.rb:54:in`run_initializers'
    from /Users/ali/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/railties-3.2.12/lib/rails/application.rb:136:in `initialize!'
    from /Users/ali/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/railties-3.2.12/lib/rails/railtie/configurable.rb:30:in`method_missing'
    from /Users/ali/src/cloud_analytics/config/environment.rb:16:in `<top (required)>'
    from /Users/ali/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in`require'
    from /Users/ali/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `block in require'
    from /Users/ali/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:236:in`load_dependency'
    from /Users/ali/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `require'
    from /Users/ali/src/cloud_analytics/config.ru:3:in`block in <main>'
    from /Users/ali/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/rack-1.4.5/lib/rack/builder.rb:51:in `instance_eval'
    from /Users/ali/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/rack-1.4.5/lib/rack/builder.rb:51:in`initialize'
    from /Users/ali/src/cloud_analytics/config.ru:in `new'
    from /Users/ali/src/cloud_analytics/config.ru:in`<main>'
    from /Users/ali/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/rack-1.4.5/lib/rack/builder.rb:40:in `eval'
    from /Users/ali/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/rack-1.4.5/lib/rack/builder.rb:40:in`parse_file'
    from /Users/ali/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/rack-1.4.5/lib/rack/server.rb:200:in `app'
    from /Users/ali/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/railties-3.2.12/lib/rails/commands/server.rb:46:in`app'
    from /Users/ali/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/rack-1.4.5/lib/rack/server.rb:304:in `wrapped_app'
    from /Users/ali/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/rack-1.4.5/lib/rack/server.rb:254:in`start'
    from /Users/ali/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/railties-3.2.12/lib/rails/commands/server.rb:70:in `start'
    from /Users/ali/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/railties-3.2.12/lib/rails/commands.rb:55:in`block in <top (required)>'
    from /Users/ali/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/railties-3.2.12/lib/rails/commands.rb:50:in `tap'
    from /Users/ali/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/railties-3.2.12/lib/rails/commands.rb:50:in`<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in`<main>'

**Comment by thomasdavis** [comment]
Getting the same.
