### ISSUE TITLE
Regression: Rails.cache.read_multi with array parameter returns empty hash

### ISSUE THREAD

**Issue by adorr** [petergoldstein/dalli#377]
I'm using rails 3.1.12, ruby 1.9.3p327, dalli 2.6.4

Steps to reproduce:

1. Create a new rails project
2. Add dalli to gemfile and bundle install
3. set config.cache_store = :dalli_store in config/environments/development.rb
4. load rails console
5. run these commands:

    Rails.cache.write "a", "a"
    Rails.cache.write "b", "b"
    Rails.cache.read_multi ["a", "b"]

6. Expected: { "a" => "a", "b" => "b" }, Returned: { }

Rails.cache.read_multi "a", "b" works, but it does not work with an array as the parameter.

This does return the expected result with dalli 2.6.2

**Comment by petergoldstein** [comment]
As we're about to release version 2.7.5, and this issue is basically a versioning discussion from 2.6.x / 2013, I'm going to close this issue.
