### ISSUE TITLE
Unexpected exception in Dalli: NameError: uninitialized constant ActiveRecord::ConnectionAdapters::MysqlAdapter

### ISSUE THREAD

**Issue by abarriga** [petergoldstein/dalli#386]
The error shows:
This is a bug in Dalli, please enter an issue in Github if it does not already exist.

dalli-e7dae61d9418/lib/dalli/server.rb:424:in `deserialize'
dalli-e7dae61d9418/lib/dalli/server.rb:480:in `generic_response'
dalli-e7dae61d9418/lib/dalli/server.rb:257:in `get'
dalli-e7dae61d9418/lib/dalli/server.rb:60:in `request'
dalli-e7dae61d9418/lib/dalli/options.rb:18:in `block in request'

**Comment by petergoldstein** [comment]
Contrary to the error message, this was almost certainly not an error in Dalli.  Closing.
