### ISSUE TITLE
A beginners' tutorial in pure Ruby?

### ISSUE THREAD

**Issue by smtalim** [petergoldstein/dalli#388]
A lot of students new to Ruby (and not knowing Rails) are looking out for some tutorial on how to use dalli with maybe the activerecord gem but the code being in pure Ruby. Anyone game for writing this for them?

Much appreciated.

**Comment by petergoldstein** [comment]
This really doesn't make sense to me.  The documentation on how to use Dalli::Client is reasonably clear, and a good Ruby programmer should be able to understand Dalli based on existing documentation.  I don't see what such a tutorial would add.  If needed, someone should write it as a blog post.
