### ISSUE TITLE
Add API to manipulate CAS better

### ISSUE THREAD

**Issue by arthurnn** [petergoldstein/dalli#389]
I have some use cases that using the `client.cas { |v| .. }` with a block just doesnt make sense.
For instance, I need to set passing a cas only if the value exists, otherwise I would do an `add`. 
Right now I can use the private method perform, but it doesn't seem correct:
```ruby
v, cas = client.send(:perform, :cas, 'foo')
if v.nil?
  client.add('foo', 222)
else
  client.send(:perform, :set, 'foo', 999, 0, cas, {})
end
```

Let me know if that make sense or not. Also if it does I will be glad to submit a PR for this feature.

**Comment by petergoldstein** [comment]
Given that PR #398 was merged in, I'm going to close this issue as resolved.
