### ISSUE TITLE
Dalli returning true:TrueClass on memcached node reboot

### ISSUE THREAD

**Issue by mheffner** [petergoldstein/dalli#390]
Seems related to #146, but we appear to see a similar problem with the latest dalli when a memcached node is rebooted.

When we reboot a node in our Elasticache, memcached 1.4.5, cluster under load we see numerous failures from `get` returning `true:TrueClass` instead of the cached object (or simply nil).

memcached 1.4.5
dalli 2.6.4
ruby 1.9.3-p429

Using the connection settings:

```ruby
    CLIENT_SETTINGS = {
      # Default TTL
      :expires_in => 3600,
      # Don't move keys to failed hosts
      :failover => false,
      :down_retry_delay => 30
    }
```

Unfortunately I haven't been able to come up with a case that reproduces this. Anything to check to help debug this?

**Comment by petergoldstein** [comment]
This issue never got much follow up, and there have been no other similar reports.  As the issue hasn't been commented on in over 2 years, I'm going to close.

@mheffner Please reopen if this is still an issue.  Thanks!

**Comment by cryptomail** [comment]
We can confirm we were afflicted with this.  There appears to be a state on AWS Elasticache that is 1/2 baked, where the server accepts connections, yet has no data initialized and then simply returns status === 0 with no data 🥰 
It's still an issue and my partner @snbloch and I tried very naively to fix it but we blew all the tests up lol.
Honestly we feel it's a problem with memcached implementors.  Why accept connections and afford ANY response when you (sorry for the anthropomorphism) haven't loaded all your data yet, and truly aren't ready?!
I'm still wondering if there is some path that can detect this state in Dalli, and afford an error state to clients.

Our use case happens to be very fortunate in that we can detect this state higher up as a client of this library, and can rule out the silly True Object from being returned, but that's no way to live really either :)

Thank you for your continued support on Dalli.
