### ISSUE TITLE
Output a warning when expires_in option in fetch doesn't match stored value

### ISSUE THREAD

**Issue by pierpaolofrasa-twt** [petergoldstein/dalli#394]
If I store a value with an expiration time of, say, 1 day, and later I make a call such as this one:
`
Rails.cache.fetch('xy', expires_in: 10.seconds) { get_xy }
`

The method silently fails to reload the data after 10 seconds. This may be obvious to people who are well acquainted with memcached (which I'm not), but maybe it would be nice if in such a case a warning could be ouput, e.g. "expires_in option already set, update or flush the cache to set new expiration time". This would have saved me one hour of debugging time.

Is it even possible to change this within dalli or is this an issue with Rails caching in general?

**Comment by petergoldstein** [comment]
So what you describe isn't really possible because of how Memcached and Rails.cache work.  Closing.
