### ISSUE TITLE
delete_matched for  ActiveSupport::Cache::DalliStore

### ISSUE THREAD

**Issue by equivalent** [petergoldstein/dalli#397]
Hi, 

I just want to ask what would you recommend to fake  functionality  of `delete_matched` for `ActiveSupport::Cache::DalliStore`  the only solution that I found is : 

* http://www.moleculardensity.net/blog/posts/2
* https://github.com/Phobos98/dalli-delete-matched

...would you go with this ?

Also, I kinda get that Dalli doesn't have any build in functionality to match keys so that application need to do it manually, however it seems to me strange why. Could you explain it to me why ?

**Comment by petergoldstein** [comment]
Per @kikan that's exactly why it isn't supported in `ActiveSupport::Cache::DalliStore`.  Not planning to add this feature.  Closing.
