### ISSUE TITLE
Dynamically namespace

### ISSUE THREAD

**Issue by diegonogueira** [petergoldstein/dalli#399]
Hi!

There is a way to change dynamically the namespace? I have a multi tenancy app, i need to change the namespace with Apartment::Database.current_database ( apartment gem ).

Using default rails cache, i did:

``` ruby
module ActiveSupport
  module Cache
    class Store
      def options
        @options.merge(namespace: Apartment::Database.current_database)
      end
    end
  end
end
```

With the code above, the Rails.cache.fetch, delete, write, read and cache helper method using cache_digest works fine! But now, i need to do this with dalli gem for production environment.

Any ideas? configurations?

Thanks,
Diego

**Comment by botsarenthuman** [comment]
I wonder if this is still relevant? I.e. does it have threading implications?
