### ISSUE TITLE
"No server available" error on bad parameter

### ISSUE THREAD

**Issue by tjchambers** [petergoldstein/dalli#400]
I was trying to understand how some of my code was getting a No server available when it was available. I was able to isolate the problem to a bad parameter to incr method. 

The code that creates this error is https://gist.github.com/tjchambers/7213452 and the
results from running the code are: https://gist.github.com/tjchambers/7213479 .

I do not receive the internal error that is reported when I run my code, just the Dalli::RingError: No server available which is obviously not the correct error for the condition.

**Comment by jstejada** [comment]
:+1: any updates on this? I'm having the same issue, getting a RingError, but my memcached server is definitely up. Still haven't figured out what the real cause is, but I think it is because of this

**Comment by inspire22** [comment]
Previously, sending an invalid key (i.e. a space or quote in it) would sometimes affect this and/or show an odd downtime message - not sure if that's still an issue or not.  Also check your memcached version...

**Comment by petergoldstein** [comment]
This should be fixed by #582
