### ISSUE TITLE
Client flush method takes a delay but does not use it

### ISSUE THREAD

**Issue by breakpointer** [petergoldstein/dalli#410]
Hello, I'd like to use the delay option on the client `flush` method however there is no explanation of how to use it and walking through the code I can't actually figure out what the 'delay' param does. It appears to do nothing.

I'm interested in using this delay feature because we have over a dozen memcached severs and we'd like to stagger our cache flushing. This delay param seems perfect but I'm not going to use it until I can understand how it works.

It's here on the client https://github.com/mperham/dalli/blob/master/lib/dalli/client.rb#L251
which is called on each of my servers here via `request`
https://github.com/mperham/dalli/blob/master/lib/dalli/server.rb#L56
which in turn, calls `send(:flush, delay)`
Looking at the method `flush` it takes a 'ttl' param but then does not use it?
https://github.com/mperham/dalli/blob/master/lib/dalli/server.rb#L305

I see ttl passed in to the binary protocol packing in other places... like here https://github.com/mperham/dalli/blob/master/lib/dalli/server.rb#L381

I'm happy to fork, fix, and issue a PR if this is indeed not implemented. I'm just a little confused at the moment. 

Thanks!

**Comment by petergoldstein** [comment]
@breakpointer Did you ever put together some code here?

**Comment by breakpointer** [comment]
@petergoldstein Oh, hmm... If I did it's long gone by now. Sorry!

**Comment by petergoldstein** [comment]
@breakpointer Ok, thanks.

I'll schedule this for review in 3.0.
