### ISSUE TITLE
TypeError: no implicit conversion of ActiveSupport::TimeWithZone into Integer

### ISSUE THREAD

**Issue by ActualAl** [petergoldstein/dalli#412]
HI I've checked the closed issues but couldn't find an issue relating to this TypeError. Has anyone seen this? I'm using dalli-2.6.4

Unexpected exception in Dalli: TypeError: no implicit conversion of ActiveSupport::TimeWithZone into Integer
This is a bug in Dalli, please enter an issue in Github if it does not already exist.

/var/www/site/shared/bundle/ruby/2.0.0/gems/dalli-2.6.4/lib/dalli/server.rb:272:in `pack'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/dalli-2.6.4/lib/dalli/server.rb:272:in `block in set'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/dalli-2.6.4/lib/dalli/server.rb:458:in `guard_max_value'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/dalli-2.6.4/lib/dalli/server.rb:271:in `set'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/dalli-2.6.4/lib/dalli/server.rb:60:in `request'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/dalli-2.6.4/lib/dalli/options.rb:18:in `block in request'
        /usr/local/rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/dalli-2.6.4/lib/dalli/options.rb:17:in `request'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/dalli-2.6.4/lib/dalli/client.rb:348:in `perform'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/dalli-2.6.4/lib/dalli/client.rb:199:in `set'
        (eval):7:in `block in set_with_newrelic_trace'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.6.6.147/lib/new_relic/agent/method_tracer.rb:268:in `trace_execution_scoped'
        (eval):4:in `set_with_newrelic_trace'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/dalli-2.6.4/lib/active_support/cache/dalli_store.rb:244:in `write_entry'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/activesupport-3.2.13/lib/active_support/cache/strategy/local_cache.rb:140:in `write_entry'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/dalli-2.6.4/lib/active_support/cache/dalli_store.rb:106:in `block in write'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/dalli-2.6.4/lib/active_support/cache/dalli_store.rb:291:in `block in instrument'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/activesupport-3.2.13/lib/active_support/notifications.rb:125:in `instrument'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/dalli-2.6.4/lib/active_support/cache/dalli_store.rb:291:in `instrument'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/dalli-2.6.4/lib/active_support/cache/dalli_store.rb:105:in `write'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/dalli-2.6.4/lib/active_support/cache/dalli_store.rb:82:in `fetch'
        /var/www/site/releases/20131202132530/app/models/reporting.rb:8:in `sold_contract_data'
        /var/www/site/releases/20131202132530/app/models/reporting.rb:27:in `sold_contract_revenue_grouped_by_created_date'
        /var/www/site/releases/20131202132530/app/models/reporting.rb:38:in `block in sold_contract_revenue_for_team_grouped_by_created_date'
        /var/www/site/releases/20131202132530/app/models/reporting.rb:37:in `collect'
        /var/www/site/releases/20131202132530/app/models/reporting.rb:37:in `sold_contract_revenue_for_team_grouped_by_created_date'
        /var/www/site/releases/20131202132530/app/views/dashboards/_team_performance_table.html.haml:10:in `block in _app_views_dashboards__team_performance_table_html_haml__823592184218940836_59233320'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/haml-4.0.0/lib/haml/helpers/action_view_mods.rb:45:in `block in capture_with_haml'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/haml-4.0.0/lib/haml/helpers.rb:368:in `call'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/haml-4.0.0/lib/haml/helpers.rb:368:in `block in capture_haml'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/haml-4.0.0/lib/haml/helpers.rb:603:in `with_haml_buffer'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/haml-4.0.0/lib/haml/helpers.rb:364:in `capture_haml'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/haml-4.0.0/lib/haml/helpers/xss_mods.rb:61:in `capture_haml_with_haml_xss'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/haml-4.0.0/lib/haml/helpers/action_view_mods.rb:45:in `capture_with_haml'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_view/helpers/capture_helper.rb:138:in `content_for'
        /var/www/site/releases/20131202132530/app/views/dashboards/_team_performance_table.html.haml:3:in `_app_views_dashboards__team_performance_table_html_haml__823592184218940836_59233320'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_view/template.rb:145:in `block in render'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/activesupport-3.2.13/lib/active_support/notifications.rb:125:in `instrument'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_view/template.rb:143:in `render'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/rack-mini-profiler-0.1.29/Ruby/lib/mini_profiler/profiling_methods.rb:90:in `block in profile_method'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_view/renderer/partial_renderer.rb:265:in `render_partial'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_view/renderer/partial_renderer.rb:238:in `block in render'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/activesupport-3.2.13/lib/active_support/notifications.rb:123:in `block in instrument'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/activesupport-3.2.13/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/activesupport-3.2.13/lib/active_support/notifications.rb:123:in `instrument'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_view/renderer/partial_renderer.rb:237:in `render'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.6.6.147/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:176:in `block in render_with_newrelic'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_view/renderer/renderer.rb:41:in `render_partial'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_view/helpers/rendering_helper.rb:27:in `render'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/haml-4.0.0/lib/haml/helpers/action_view_mods.rb:10:in `block in render_with_haml'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/haml-4.0.0/lib/haml/helpers.rb:89:in `non_haml'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/haml-4.0.0/lib/haml/helpers/action_view_mods.rb:10:in `render_with_haml'
        /var/www/site/releases/20131202132530/app/views/dashboards/show.html.haml:41:in `block in _app_views_dashboards_show_html_haml__2939825893598334970_54831920'
        /var/www/site/releases/20131202132530/app/views/dashboards/show.html.haml:38:in `each'
        /var/www/site/releases/20131202132530/app/views/dashboards/show.html.haml:38:in `_app_views_dashboards_show_html_haml__2939825893598334970_54831920'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_view/template.rb:145:in `block in render'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/activesupport-3.2.13/lib/active_support/notifications.rb:125:in `instrument'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_view/template.rb:143:in `render'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/rack-mini-profiler-0.1.29/Ruby/lib/mini_profiler/profiling_methods.rb:90:in `block in profile_method'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_view/renderer/template_renderer.rb:47:in `block (2 levels) in render_template'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/activesupport-3.2.13/lib/active_support/notifications.rb:123:in `block in instrument'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/activesupport-3.2.13/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/activesupport-3.2.13/lib/active_support/notifications.rb:123:in `instrument'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_view/renderer/template_renderer.rb:46:in `block in render_template'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_view/renderer/template_renderer.rb:54:in `render_with_layout'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_view/renderer/template_renderer.rb:45:in `render_template'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_view/renderer/template_renderer.rb:18:in `render'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.6.6.147/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:160:in `block in render_with_newrelic'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.6.6.147/lib/new_relic/agent/method_tracer.rb:268:in `trace_execution_scoped'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.6.6.147/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:159:in `render_with_newrelic'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_view/renderer/renderer.rb:36:in `render_template'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_view/renderer/renderer.rb:17:in `render'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/abstract_controller/rendering.rb:110:in `_render_template'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_controller/metal/streaming.rb:225:in `_render_template'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/abstract_controller/rendering.rb:103:in `render_to_body'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_controller/metal/renderers.rb:28:in `render_to_body'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_controller/metal/compatibility.rb:50:in `render_to_body'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/abstract_controller/rendering.rb:88:in `render'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_controller/metal/rendering.rb:16:in `render'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_controller/metal/instrumentation.rb:40:in `block (2 levels) in render'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/activesupport-3.2.13/lib/active_support/core_ext/benchmark.rb:5:in `block in ms'
        /usr/local/rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/benchmark.rb:296:in `realtime'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/activesupport-3.2.13/lib/active_support/core_ext/benchmark.rb:5:in `ms'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_controller/metal/instrumentation.rb:40:in `block in render'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_controller/metal/instrumentation.rb:83:in `cleanup_view_runtime'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_controller/metal/instrumentation.rb:39:in `render'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_controller/metal/implicit_render.rb:10:in `default_render'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_controller/metal/implicit_render.rb:5:in `send_action'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/abstract_controller/base.rb:167:in `process_action'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_controller/metal/rendering.rb:10:in `process_action'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:480:in `_run__4444593686888914580__process_action__476359674342475331__callbacks'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:405:in `__run_callback'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:81:in `run_callbacks'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/abstract_controller/callbacks.rb:17:in `process_action'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_controller/metal/rescue.rb:29:in `process_action'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/activesupport-3.2.13/lib/active_support/notifications.rb:123:in `block in instrument'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/activesupport-3.2.13/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/activesupport-3.2.13/lib/active_support/notifications.rb:123:in `instrument'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.6.6.147/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:38:in `block in process_action'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.6.6.147/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:318:in `perform_action_with_newrelic_trace'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.6.6.147/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:37:in `process_action'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/abstract_controller/base.rb:121:in `process'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/abstract_controller/rendering.rb:45:in `process'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/rack-mini-profiler-0.1.29/Ruby/lib/mini_profiler/profiling_methods.rb:90:in `block in profile_method'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_controller/metal.rb:203:in `dispatch'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_controller/metal.rb:246:in `block in action'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_dispatch/routing/route_set.rb:73:in `call'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_dispatch/routing/route_set.rb:36:in `call'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_dispatch/routing/route_set.rb:612:in `call'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/omniauth-1.1.3/lib/omniauth/strategy.rb:177:in `call!'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/omniauth-1.1.3/lib/omniauth/strategy.rb:157:in `call'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/omniauth-1.1.3/lib/omniauth/builder.rb:48:in `call'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.6.6.147/lib/new_relic/rack/error_collector.rb:43:in `call'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.6.6.147/lib/new_relic/rack/agent_hooks.rb:22:in `call'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.6.6.147/lib/new_relic/rack/browser_monitoring.rb:16:in `call'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/etag.rb:23:in `call'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/conditionalget.rb:25:in `call'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_dispatch/middleware/head.rb:14:in `call'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_dispatch/middleware/flash.rb:242:in `call'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:210:in `context'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:205:in `call'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_dispatch/middleware/cookies.rb:341:in `call'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:405:in `_run__4277526774857212090__call__3217253834797347184__callbacks'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:405:in `__run_callback'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:81:in `run_callbacks'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/airbrake-3.1.8/lib/airbrake/rails/middleware.rb:15:in `call'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/railties-3.2.13/lib/rails/rack/logger.rb:32:in `call_app'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/railties-3.2.13/lib/rails/rack/logger.rb:16:in `block in call'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/activesupport-3.2.13/lib/active_support/tagged_logging.rb:22:in `tagged'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/railties-3.2.13/lib/rails/rack/logger.rb:16:in `call'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_dispatch/middleware/request_id.rb:22:in `call'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/methodoverride.rb:21:in `call'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/runtime.rb:17:in `call'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/rocket_pants-1.9.1/lib/rocket_pants/cache_middleware.rb:21:in `_call'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/rocket_pants-1.9.1/lib/rocket_pants/cache_middleware.rb:12:in `call'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/activesupport-3.2.13/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/lock.rb:15:in `call'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:136:in `forward'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:245:in `fetch'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:185:in `lookup'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:66:in `call!'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:51:in `call'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/airbrake-3.1.8/lib/airbrake/user_informer.rb:16:in `_call'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/airbrake-3.1.8/lib/airbrake/user_informer.rb:16:in `_call'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/airbrake-3.1.8/lib/airbrake/user_informer.rb:12:in `call'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/rack-mini-profiler-0.1.29/Ruby/lib/mini_profiler/profiler.rb:188:in `call'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/railties-3.2.13/lib/rails/engine.rb:479:in `call'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/railties-3.2.13/lib/rails/application.rb:223:in `call'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/railties-3.2.13/lib/rails/railtie/configurable.rb:30:in `method_missing'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/unicorn-4.6.2/lib/unicorn/http_server.rb:552:in `process_client'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/unicorn-4.6.2/lib/unicorn/http_server.rb:632:in `worker_loop'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.6.6.147/lib/new_relic/agent/instrumentation/unicorn_instrumentation.rb:22:in `call'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.6.6.147/lib/new_relic/agent/instrumentation/unicorn_instrumentation.rb:22:in `block (4 levels) in <top (required)>'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/unicorn-4.6.2/lib/unicorn/http_server.rb:500:in `spawn_missing_workers'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/unicorn-4.6.2/lib/unicorn/http_server.rb:142:in `start'
        /var/www/site/shared/bundle/ruby/2.0.0/gems/unicorn-4.6.2/bin/unicorn:126:in `<top (required)>'
        /var/www/site/shared/bundle/ruby/2.0.0/bin/unicorn:23:in `load'
        /var/www/site/shared/bundle/ruby/2.0.0/bin/unicorn:23:in `<main>'

**Comment by petergoldstein** [comment]
The sanitize_ttl will now call to_i on the ttl value, so values like `5.minutes` should work.  Closing this issue.
