### ISSUE TITLE
Support alternate hashing algorithms (other than the default Ketama)

### ISSUE THREAD

**Issue by drasch** [petergoldstein/dalli#413]
We're attempting to use Dalli in conjunction with a second memcache client (twemproxy).  

In testing this we've found that the hashing algorithms don't match up.  

Is the hashing algorithm compatible with other implementations and we're doing something wrong, or alternatively would you be receptive to a patch to offer additional or even change the hashing algorithm to Ketama?

Thanks,
David

**Comment by ashishgpersonal** [comment]
Hi, did this get resolved? We are trying to figure out how to make dalli's hashing identical to the AWS java memcached client, and are stuck. Any suggestions?

**Comment by zmack** [comment]
Not quite. I remember that the algo being used in dalli was yielding significantly different results than what twemproxy was getting is while also on 'ketama' hashing.

Given that changing the implementation in dalli is sure to break a ton of people's apps, the proposed suggestion at the time was to make the algo pluggable, which was implemented in #415.

Never really got that one over the line though, given that the project i needed it for went a different way.

If you're so inclined, you could potentially take that and see if you can't get a ring algo out that matches the aws memcached client.

**Comment by ashishgpersonal** [comment]
Thanks. I wrote a custom hash for Dalli, but alas, it seems hard to exactly match the aws client implementation. Will try again soon and report back if I succeed.

**Comment by petergoldstein** [comment]
@ashishgpersonal Did you ever make any headway on matching the AWS client implementation?

**Comment by ashishgpersonal** [comment]
No, our use case went away. Our plan if it comes back is to override the
java method instead.

**Comment by vitobotta** [comment]
Hi, I'm trying to share a cache between Rails and Nginx for full page caching controlled by Rails. I got it working just fine with one memcached server, but not with multiple instances. Has anyone found out how to make this work? Thanks
