### ISSUE TITLE
Unexpected exception in Dalli: NameError: uninitialized constant AvatarUploader::Uploader69839466811780

### ISSUE THREAD

**Issue by i8ramin** [petergoldstein/dalli#455]
```
Unexpected exception in Dalli: NameError: uninitialized constant AvatarUploader::Uploader69839466811780
This is a bug in Dalli, please enter an issue in Github if it does not already exist.
```

Don't have a lot of detail about this error other than it seems to be related to marshalling and unmarshalling of Carrierwave Uploader objects.

Our workaround for the time being has been to simply exclude the uploader objects from our json outputs before caching them using Rails.cache.

Any help or information would be greatly appreciated.

**Comment by fuyi** [comment]
+1

**Comment by sunil-shrestha** [comment]
+1

**Comment by lambda2** [comment]
+1

**Comment by dylandrop** [comment]
+1
