### ISSUE TITLE
No server available (from time to time)

### ISSUE THREAD

**Issue by maxguzenski** [petergoldstein/dalli#457]
First at all, I dont sure, but maybe it is a #400 related

I have a aws cloud config running 4 instances of a c3.large with 4 unicorn fork on each and I have a cluster of memcache ElastiCache (xlarge) (just 1 instance) .

When My website is very busy (+/- 2600 online users) each 30 or 40min, new relic show a huge peak of about 2min, and I can see on rails log:

notice xxxx.cfg.use1.cache.amazonaws.com:11211 is down - instance1
warning DalliError: No server available - instance1
notice xxxx.cfg.use1.cache.amazonaws.com:11211 is down - instance2
warning DalliError: No server available - instance2

...

notice d4-memcache-xlarge.0ctbwl.cfg.use1.cache.amazonaws.com:11211 is back (downtime was 1.008 seconds) | instance1
warning message repeated 106 times: [ DalliError: No server available] | instance1
notice d4-memcache-xlarge.0ctbwl.cfg.use1.cache.amazonaws.com:11211 is back (downtime was 1.008 seconds) | instance1

-> this will repeat for 1min to 2min and finally, work again.

anyone have any idea why?

**Comment by joshuasiler** [comment]
I'd better your latencies to connect are spiking to more than 500ms (which is the dalli default.)

**Comment by extrail** [comment]
Just started experiencing the same issue.
Did anybody reach a solution

**Comment by rgaufman** [comment]
I have something similar, reported here: https://github.com/petergoldstein/dalli/issues/727

**Comment by rylanb** [comment]
I have this happen on heroku using memcached-cloud. It either resolves itself or I have to trigger a restart of the server. 

I'm kind of lost on how to fix that as it works for days on end w/o any problems. Then just stops working for a few minutes and then comes back (usually automatically). I guess network gremlins are pulling wires out?
