### ISSUE TITLE
Strange response when reading a value of created-by-increment counter for the first time

### ISSUE THREAD

**Issue by snicky** [petergoldstein/dalli#463]
Testing dalli_store:

`@dalli.increment('counter', 1, initial: 5)`
> 5

`@dalli.read('counter', raw: true)`
> "5\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"

`@dalli.read('counter')`
> "5\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"

`@dalli.increment('counter', 1, initial: 5)`
> 6

`@dalli.read('counter', raw: true)`
> "6"

`@dalli.read('counter')`
> "6"

Is it expected?

**Comment by thbar** [comment]
Just some feedback: thanks for sharing this - I got bitten by it too.

The weird thing is that locally, calling `read` just after `increment` works perfectly, but in production I had the raw output for `read`, but /just/ the first time.

So it really /looked/ like a bug!

**Comment by petergoldstein** [comment]
This is behaving as expected, so closing the issue
