### ISSUE TITLE
Dalli connection pool, Heroku, Puma and Sinatra

### ISSUE THREAD

**Issue by ollie** [petergoldstein/dalli#464]
Hello,
1. Is there a way to set a connection pool size for Dalli?
2. Or get one to see its size?
3. Is it even necessary?
4. Can Dalli be used in multiprocess webserver?
5. Are there some caveats like clearing connection pool in Sequel before fork?

When using Heroku with Puma server, along with multiple dynos, puma wokers (processes) and threads, one needs to be careful about database, redis and memcached connections. Calculating connection pools could be fun.

We are not using Rails so I’m not sure this applies https://github.com/mperham/dalli#multithreading-and-rails.

Thank you

**Comment by Leooo** [comment]
Hi Ollie, I have the same quesitons thanks for posting this thread.

Did you manage to understand how to add a connection_pool  size for Dalli on Rack::Cache or find an alternative? Not 100% sure that's needed but on what I understand for Puma clustered it is better, I can use a connection pool for config.cache_store = :dalli_store,  { pool_size: 5} but not for Rack::Cache. Thanks.

**Comment by ollie** [comment]
@Leooo Hi Leo, no I haven't looked into it yet, not sure if I can squeeze the time for it these days. :)

**Comment by ollie** [comment]
@Leooo Ha, I forgot I opened an issue in Rack::Cache https://github.com/rtomayko/rack-cache/issues/105 but nobody replied yet.
