### ISSUE TITLE
Rails 3.2.18 dalli for session store, expires_after is ignored in session_store.rb

### ISSUE THREAD

**Issue by JoshMcKin** [petergoldstein/dalli#466]
In our `development.rb`:

```
 config.cache_store = :dalli_store, nil, {:namespace => 'portal_sessions',
                                  :expires_in  => 5.seconds,
                                  :compress => true,
                                  :pool_size => 20}
```

In our `session_store.rb`:

```
Rails.application.config.session_store ActionDispatch::Session::CacheStore, :expire_after => 20.minutes
```

Session always expires in 5 seconds, and it also appear any options passed with the above `session_store.rb` setup is ignored. Also tried using `:expires_in` instead of `:expires_after` in `session_store.rb`, but produced the same results. This may be the intended functionality but [README.md](https://github.com/mperham/dalli#usage-with-rails-3x-and-4x) would suggest otherwise.

**Comment by espen** [comment]
Related https://github.com/rails/rails/issues/17582#issuecomment-100020134
