### ISSUE TITLE
Dalli::DalliError: Response error 130: Out of memory

### ISSUE THREAD

**Issue by sumakumardey** [petergoldstein/dalli#476]
Dalli::DalliError: Response error 130: Out of memory
from /bundled_gems/ruby/1.9.1/gems/dalli-2.7.0/lib/dalli/server.rb:496:in `cas_response'
        from /bundled_gems/ruby/1.9.1/gems/dalli-2.7.0/lib/dalli/server.rb:275:in `block in set'
        from /bundled_gems/ruby/1.9.1/gems/dalli-2.7.0/lib/dalli/server.rb:459:in `guard_max_value'
        from /bundled_gems/ruby/1.9.1/gems/dalli-2.7.0/lib/dalli/server.rb:272:in `set'
        from /bundled_gems/ruby/1.9.1/gems/dalli-2.7.0/lib/dalli/server.rb:60:in `request'
        from /bundled_gems/ruby/1.9.1/gems/dalli-2.7.0/lib/dalli/options.rb:18:in `block in request'
        from /usr/lib64/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
        from /bundled_gems/ruby/1.9.1/gems/dalli-2.7.0/lib/dalli/options.rb:17:in `request'
        from /bundled_gems/ruby/1.9.1/gems/dalli-2.7.0/lib/dalli/client.rb:323:in `perform'
        from /bundled_gems/ruby/1.9.1/gems/dalli-2.7.0/lib/dalli/client.rb:103:in `set'
        from (irb):13
        from /usr/bin/irb:12:in `<main>'

Can some one explain this error ? i see there is lot of empty space in memcache but still i am getting this error for few keys .

**Comment by petergoldstein** [comment]
@sumakumardey I'm closing this, as @dfens answer seems the most likely explanation, and there hasn't been any response or follow up for over a year.

Please reopen if @dfens response doesn't address your question, and include answers to his questions.  Thanks!

**Comment by mcohen9** [comment]
@sumakumardey @dfens @petergoldstein 
I am having the same issue now 

I already have memcached started as:
`/usr/bin/memcached -m 2000 -I 128  -p 11211 -u memcache -l 127.0.0.1`
And this in my production.rb file 
`config.cache_store = :dalli_store, {:value_max_bytes => 5.megabytes} `

Why am i still getting this error?

**Comment by dfens** [comment]
Please check manual:
`  -m <num>
              Use <num> MB memory max to use for object storage; the default is 64 megabytes.`

By running command  with `-m 2000` you reduced max size of object to 2 megabytes

**Comment by dfens** [comment]
Please check:
```    -I <size>
              Override  the  default size of each slab page. Default is 1mb. Default is 1m, minimum is 1k, max is 128m. Adjusting this value changes the item size
              limit.  Beware that this also increases the number of slabs (use -v to view), and the overal memory usage of memcached.
``` it might affect your test, this value is in bytes

**Comment by mcohen9** [comment]
Are you saying i should write 128000 instead of 128?
`/usr/bin/memcached -m 2000 -I 128000 -p 11211 -u memcache -l 127.0.0.1`
