### ISSUE TITLE
Unexpected exception Rack Timeout

### ISSUE THREAD

**Issue by ranakhalil** [petergoldstein/dalli#478]
Hi,

I got the following error via Dalli and am not sure what the issue is:

Unexpected exception in Dalli: Rack::Timeout::RequestTimeoutError: Request ran for longer than 0.11218305564538511 seconds.
2014-08-11T23:51:23.960336+00:00 app[web.1]: [c93fb0ac-9689-4295-a504-bc597685f83c] [199.27.79.22] This is a bug in Dalli, please enter an issue in Github if it does not already exist.

Have your team experienced this issue before? Everything was working ordinarily until suddenly Dalli crashed our RubyonRails app.

Thanks,

Rana

**Comment by petergoldstein** [comment]
@ranakhalil This looks like a timeout error, presumably when writing to the underlying Memcached implementation.  Are you sure your Memcached instance was behaving properly?

Closing, as this is over a year old and we haven't seen other, similar reports.  Please reopen if this is still an issue.

**Comment by askumarks** [comment]
This issue has happend for me also. what could be the reason..?

`219 <190>1 2016-07-17T21:00:55.451768+00:00 app web.1 - - source=rack-timeout id=41a765b6-1fd7-4c7d-b707-d5197ff9e06f age=9ms timeout=25000ms duration=25000ms state=timed_out at=error
200 <190>1 2016-07-17T21:00:55.452258+00:00 app web.1 - - Unexpected exception in Dalli: Rack::Timeout::RequestTimeoutError: Request ran for longer than 25 seconds.
179 <190>1 2016-07-17T21:00:55.452271+00:00 app web.1 - - This is a bug in Dalli, please enter an issue in Github if it does not already exist.
177 <190>1 2016-07-17T21:00:55.452379+00:00 app web.1 - - /app/vendor/bundle/ruby/1.9.1/gems/dalli-1.1.2/lib/dalli/socket.rb:101:in `sysread'
188 <190>1 2016-07-17T21:00:55.452380+00:00 app web.1 - - 	/app/vendor/bundle/ruby/1.9.1/gems/dalli-1.1.2/lib/dalli/socket.rb:101:in `block in readfull'
175 <190>1 2016-07-17T21:00:55.452381+00:00 app web.1 - - 	/app/vendor/bundle/ruby/1.9.1/gems/dalli-1.1.2/lib/dalli/socket.rb:100:in `loop'
179 <190>1 2016-07-17T21:00:55.452381+00:00 app web.1 - - 	/app/vendor/bundle/ruby/1.9.1/gems/dalli-1.1.2/lib/dalli/socket.rb:100:in `readfull'
175 <190>1 2016-07-17T21:00:55.452382+00:00 app web.1 - - 	/app/vendor/bundle/ruby/1.9.1/gems/dalli-1.1.2/lib/dalli/server.rb:374:in `read'
187 <190>1 2016-07-17T21:00:55.452382+00:00 app web.1 - - 	/app/vendor/bundle/ruby/1.9.1/gems/dalli-1.1.2/lib/dalli/server.rb:317:in `generic_response'
174 <190>1 2016-07-17T21:00:55.452383+00:00 app web.1 - - 	/app/vendor/bundle/ruby/1.9.1/gems/dalli-1.1.2/lib/dalli/server.rb:146:in `get'
177 <190>1 2016-07-17T21:00:55.452383+00:00 app web.1 - - 	/app/vendor/bundle/ruby/1.9.1/gems/dalli-1.1.2/lib/dalli/server.rb:46:in `request'
187 <190>1 2016-07-17T21:00:55.452383+00:00 app web.1 - - 	/app/vendor/bundle/ruby/1.9.1/gems/dalli-1.1.2/lib/dalli/options.rb:18:in `block in request'
168 <190>1 2016-07-17T21:00:55.452384+00:00 app web.1 - - 	/app/vendor/ruby-1.9.2/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
178 <190>1 2016-07-17T21:00:55.452385+00:00 app web.1 - - 	/app/vendor/bundle/ruby/1.9.1/gems/dalli-1.1.2/lib/dalli/options.rb:17:in `request'
178 <190>1 2016-07-17T21:00:55.452385+00:00 app web.1 - - 	/app/vendor/bundle/ruby/1.9.1/gems/dalli-1.1.2/lib/dalli/client.rb:252:in `perform'
173 <190>1 2016-07-17T21:00:55.452386+00:00 app web.1 - - 	/app/vendor/bundle/ruby/1.9.1/gems/dalli-1.1.2/lib/dalli/client.rb:61:in `get'`
