### ISSUE TITLE
Catching MarshalError

### ISSUE THREAD

**Issue by pitr** [petergoldstein/dalli#480]
This code [1] prints MarshalError details to logger and returns silently. I'd like to catch those exceptions and log in a third-party service, like Honeybadger, airbrake, NewRelic, etc. What's the best way to do this?

[1] https://github.com/mperham/dalli/blob/v2.7.2/lib/dalli/server.rb#L63-L67

**Comment by mylescc** [comment]
:+1: We've been missing a bug in our system due to this silent logging of the error. Would be create to have an easy way to get the error reporting into Rollbar/Newrelic

**Comment by volkanunsal** [comment]
Any progress on this? It's really awful that I have to dig out these errors from log files.

**Comment by sbungartz** [comment]
Hi, we just came across this issue as well: we had errors when unmarshalling cache entries created in older versions and one broken entry caused dalli to skip using the cache for 60 seconds without any notification.

I feel like it would still help a lot of people to have something like #482 for the 2.x branch and just point that out in the README.
