### ISSUE TITLE
Getting this issue: NetworkError: Socket operation failed, retrying...

### ISSUE THREAD

**Issue by sbatbayar** [petergoldstein/dalli#484]
Hi i'm using cache to serve user's request on rails project. It's working fine but sometimes getting following error:

#<Dalli::NetworkError: Socket operation failed, retrying...>
retrying request with new server
Dalli::Server#connect localhost:11211

It makes my application loses some requests. These are configuration.

config.cache_store = :dalli_store, 'localhost:11211', {:compress => true,  :value_max_bytes => 2048576 }

Is there any solutions to this. Or i did something wrong?

**Comment by petergoldstein** [comment]
@sbatbayar As #440 has been fixed, I'm assuming this issue is resolved as well?  So I'm going to close.  If this is still a problem, please reopen.
