### ISSUE TITLE
Use ppoll under MRI1.9.3+ if available

### ISSUE THREAD

**Issue by mperham** [petergoldstein/dalli#540]
Eric Wong (MRI committer, notable GitHub non-user) sent me this git patch to improve Dalli performance:

kgio and the io/wait extension in stdlib will use the
"rb_wait_for_single_fd" function in MRI 1.9.3 and later.  Under
Linux, this allows the use of the ppoll(2) syscall which gives
consistent performance regardless of FD number.

IO.select is slower because it needs to allocate Ruby arrays for
use as arguments and return values as well as internal buffers
for the bitmap fd_set argument.  Even if the allocation overhead
were avoided, the select(2) syscall will need to perform a
linear scan over a large bitmap for a high-numbered FD.

ref: https://bugs.ruby-lang.org/issues/4531
ref: http://blade.nagaokaut.ac.jp/cgi-bin/scat.rb/ruby/ruby-core/35572

```
 ----------------------------------------------------------------
  Eric Wong (1):
        use ppoll under MRI 1.9.3+ if available

 lib/dalli/socket.rb | 7 ++++---
 1 file changed, 4 insertions(+), 3 deletions(-)

diff --git a/lib/dalli/socket.rb b/lib/dalli/socket.rb
index 87918bf..ea6895b 100644
--- a/lib/dalli/socket.rb
+++ b/lib/dalli/socket.rb
@@ -17,11 +17,11 @@ class Dalli::Server::KSocket < Kgio::Socket
     attr_accessor :options, :server

     def kgio_wait_readable
-      IO.select([self], nil, nil, options[:socket_timeout]) || raise(Timeout::Error, "IO timeout")
+      super(options[:socket_timeout]) || raise(Timeout::Error, "IO timeout")
     end

     def kgio_wait_writable
-      IO.select(nil, [self], nil, options[:socket_timeout]) || raise(Timeout::Error, "IO timeout")
+      super(options[:socket_timeout]) || raise(Timeout::Error, "IO timeout")
     end

     alias :write :kgio_write
@@ -83,6 +83,7 @@ def self.open(path, server, options = {})
   end

 rescue LoadError
+  require 'io/wait'

   puts "Using standard socket IO (#{RUBY_DESCRIPTION})" if defined?($TESTING) && $TESTING
   module Dalli::Server::KSocket
@@ -95,7 +96,7 @@ def readfull(count)
             break if value.bytesize == count
           end
         rescue Errno::EAGAIN, Errno::EWOULDBLOCK
-          if IO.select([self], nil, nil, options[:socket_timeout])
+          if wait(options[:socket_timeout])
             retry
           else
             raise Timeout::Error, "IO timeout: #{options.inspect}"
```

**Comment by petergoldstein** [comment]
@mperham Do you know if this is MRI specific code, or will this change work in Rubinius and JRuby as well?

**Comment by mperham** [comment]
The changes are to kgio- and MRI-specific code blocks.

**Comment by petergoldstein** [comment]
Got it.  Thanks.  Ok, I'll roll this into a PR and see how it runs.
