### ISSUE TITLE
Fails to retrieve values with two servers

### ISSUE THREAD

**Issue by paulmenzel** [petergoldstein/dalli#546]
With Dalli 2.7.4 storing and receiving data with two Memcached servers from two different clients fails. `memcached` is a Memcached host in the same network and `memcached-remote` is a Memcached server in a remote network. Both can be pinged.

###  Server 1 ###
```
Loading production environment (Rails 3.2.22)
irb(main):001:0> dc = Dalli::Client.new(["memcached", "memcached-remote"])
=> #<Dalli::Client:0x0000000a37d2c8 @servers=["memcached", "memcached-remote"], @options={}, @ring=nil>
irb(main):002:0> dc.set(30, "x")
=> 3320841775232319488
```

### Server 2 ###
```
Loading production environment (Rails 3.2.22)
irb(main):001:0> dc = Dalli::Client.new(["memcached", "memcached-remote"])                                                         
=> #<Dalli::Client:0x00000009f69538 @servers=["memcached", "memcached-remote"], @options={}, @ring=nil>
irb(main):002:0> dc.get(30) 
=> nil
```

Using just one Memcached server works.

### Server 1 ###
```
Loading production environment (Rails 3.2.22)
irb(main):001:0> dc = Dalli::Client.new(["memcached"])                    
=> #<Dalli::Client:0x0000000a1d7a68 @servers=["memcached"], @options={}, @ring=nil>
irb(main):002:0> dc.set(40, "x")
=> 3537014557346103296
```

### Server 2 ###
```
Loading production environment (Rails 3.2.22)
irb(main):001:0> dc = Dalli::Client.new(["memcached-remote"])
=> #<Dalli::Client:0x0000000a2c28b0 @servers=["memcached-remote"], @options={}, @ring=nil>
irb(main):002:0> dc.get(40)
=> "x"
```

Hopefully, I am not missing something obvious.

**Comment by paulmenzel** [comment]
I’ll need to verify it, but it looks like the name of the Memcached server is involved and these differ between the different servers. Here is the output with `puts` statements added for `hkey`, `entryidx` and `server.name` in the method `server_for_key` in `lib/dalli/ring.rb`.

### Server 1 ###
```
irb(main):001:0> dc = Dalli::Client.new(['memcached', 'memcached-remote'])
=> #<Dalli::Client:0x00000009ebe750 @servers=["memcached", "memcached-remote"], @options={}, @ring=nil>
irb(main):002:0> dc.get(300)
552830084
36
memcached-remote:11211
=> 300
```

### Server 2 ###
```
irb(main):001:0> dc = Dalli::Client.new(['memcached', 'memcached-remote'])
=> #<Dalli::Client:0x0000000905adf8 @servers=["memcached", "memcached-remote"], @options={}, @ring=nil>
irb(main):002:0> dc.get(300)
552830084
36
memcached-remote:11211
=> nil
```

`memcached-remote` is pointing to a different IP address, set in `/etc/hosts`.

**Comment by paulmenzel** [comment]
Using the IP addresses instead of the names works.

**Comment by paulmenzel** [comment]
Thinking about it, there is no solution to fix both cases, when you have different host names for Memcached servers and when you want to be able to move servers around and there IP address changes.

The reason in this case, why this issue came in the first place is, to use Docker containers on two different servers and then linking them together with `docker run … --link memcached:memcached memcached-remote:x.x.x.x …`.

So, this issue can be closed, I guess. But if the maintainers confirm the conclusion, maybe some comments could be added to the `README.md`.

**Comment by petergoldstein** [comment]
Per last comment, closing.
