### ISSUE TITLE
:mem_cache_store vs. :dalli_store in Rails?

### ISSUE THREAD

**Issue by wjordan** [petergoldstein/dalli#557]
It seems that Rails ActiveSupport provides a Memcached adapter [`:mem_cache_store`](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/cache/mem_cache_store.rb), that requires the `dalli` gem and provides a cache store implementation that wraps `Dalli::Client`. However, dalli also provides its own Memcached adapter, [`:dalli_store`](https://github.com/mperham/dalli/blob/master/lib/active_support/cache/dalli_store.rb) that seems to do the exact same thing. :confused: 

Could someone compare these two competing Rails cache store implementations and provide some guidelines as to when it's appropriate to use one or the other? ('Always use `:dalli_store` because it's better-maintained and tested' is an acceptable response here if that's accurate, but I don't know if that's actually the case.)

I also think it would be worth adding a mention of this in `README.md` to avoid confusion for future users who may not know the difference between the two (or even that two different implementations even exist).

**Comment by petergoldstein** [comment]
Interesting.  It looks like the Memcached adapter bundled with Rails switched to Dalli (from memcached-client) with Rails 4.0.0.

My initial instinct would be to use the DalliStore.  I do think it's probably better maintained and tested than the mem_cache_store, which seems to have had relatively few updates since the conversion to Dalli.

I'll try and take a more detailed look at the two of them to compare, and provide a more authoritative answer (an update the README) in the near future.  But for now, use DalliStore.

**Comment by wjordan** [comment]
I've spent some more time looking into the differences between these two implementations. Aside from a few bug fixes, test suites and micro-optimizations diverging a bit over the years, one of the main differences between the two implementations is that `:mem_cache_store` supports nil values and the `:race_condition_ttl` option in its `#fetch` operation implemented through an `Entry` object wrapper around all values passed to Memcached, while `:dalli_store` offers higher performance by not supporting these extra features and avoiding this extra overhead.

The two PRs I've submitted this week (#559, #560) should narrow this gap by adding both of these missing features to `DalliStore`, while not sacrificing any of its performance advantage.

Beyond that work, it should be possible to synchronize the two implementations even further (for example, by having `DalliStore` [once again](https://github.com/mperham/dalli/commit/c23810882c747e6aa677e35931942b83537704fc#diff-90586e1eaac5757610f69a1c1ae4c45eL18) inherit common functionality from the `ActiveRecord::Cache::Store` base class) so that options, feature-sets, bug-fixes and test-suites can become more consistent moving forward.

**Comment by AlexRiedler** [comment]
For future readers of this; in Rails 3.2 there was also a change which makes cache keys slightly different when the cache key argument is an Array of length 1.

See: https://github.com/petergoldstein/dalli/blob/master/lib/active_support/cache/dalli_store.rb#L345

vs.

https://github.com/rails/rails/blob/3-1-stable/activesupport/lib/active_support/cache.rb#L77

vs.

https://github.com/rails/rails/blob/3-2-stable/activesupport/lib/active_support/cache.rb#L90

We might want to consider patching this to match in Dalli ? @petergoldstein thoughts?

**Comment by dennym** [comment]
To be honest I use ActiveSupport::Cache::DalliStore because there is a documentation with all the options. MemCacheStore has one paragraph in Rails Guide. I would have to dig through rails repository to figure out where and how to the configuration gets to dalli.

**Comment by philosoralphter** [comment]
@wjordan I appreciate all your messages in this cluster of related PRs. It is all I have without digging into code to see what is going on and how i should move forward, and i don't have time for that.  I am wondering if you have any key gotchas for upgrading a production system from using dalli_store to using mem_cache_store...

Thanks for all of your info.

I really would appreciate an update to the readme, @petergoldstein.  This is a four-year long issue with the only good memcached gem.  Is rails dying?  Milestone 3 fo dalli does not seem to be coming out, and at scale we tend to have problems with things like the lack of `:race_condition_ttl`.  Can we get some clarification one way or the other?  even if @wjordan has  a Readme PR you'd be willing to merge, that could save many others a lot of time that I am now dreading wasting...
Thanks all
