### ISSUE TITLE
Rack::Session::Dalli with a ConnectionPool?

### ISSUE THREAD

**Issue by mwpastore** [petergoldstein/dalli#562]
Sorry for the vague non-issue, but I'm trying to determine how I can go about coercing/tweaking `rack/session/dalli.rb` to take a `ConnectionPool` object. I've tried passing it in as `:cache` but `Rack::Session::Dalli` expects (as I'm sure you're aware) a `Dalli::Client` that responds to the `#alive!`, `#set()`, `#delete()`, etc. methods. Should I simply use a `ConnectionPool::Wrapper`? Or is there a better way to go about this?

**Comment by mwpastore** [comment]
Also, is `Rack::Session::Dalli` thread-safe?

**Comment by petergoldstein** [comment]
When running in an environment where `env['rack.multithread']` is set to true, Rack::Session::Dalli will be thread-safe.  And unless explicitly disabled with the `threadsafe: false`  option a `Dalli::Client` will be thread-safe.

**Comment by mwpastore** [comment]
Excellent. Thanks @petergoldstein. Any thoughts on using Rack::Session::Dalli with a ConnectionPool?

**Comment by axelson** [comment]
Shouldn't this be closed by #598?

**Comment by mwpastore** [comment]
@axelson Yup. Thank you!
