### ISSUE TITLE
get_multi result contains incorrect keys when given long keys

### ISSUE THREAD

**Issue by undefinedvalue** [petergoldstein/dalli#563]
When given keys that exceed the maximum length, get_multi truncates them and adds an MD5. However, the original key is lost in this process and get_multi returns a hash using the truncated keys. This is a problem if you rely on the keys being the same.

https://github.com/mperham/dalli/blob/1f2ae986a0ec5219e2577a67c4f55665570ec8f9/lib/dalli/client.rb#L362-L365

**Comment by grosser** [comment]
FYI rails fixes this by truncating them before sending into dalli

https://github.com/rails/rails/blob/master/activesupport/lib/active_support/cache/mem_cache_store.rb#L100-L106

**Comment by sobrinho** [comment]
Bitten by that today.

Is still necessary to use the dalli cache adapter or the rails adapter these days is fast enough?
