### ISSUE TITLE
New home?

### ISSUE THREAD

**Issue by mperham** [petergoldstein/dalli#572]
@petergoldstein Did you want to move Dalli under your name?  I'm happy to move it since you're doing all the work these days.

**Comment by petergoldstein** [comment]
@mperham Yes, that probably makes sense.  I'll update the gemspec and README at the same time.  That'll reduce the number of support requests you're getting for Dalli.  :)

**Comment by mperham** [comment]
You need to delete your fork.

**Comment by petergoldstein** [comment]
Fork deleted.

**Comment by petergoldstein** [comment]
Thanks @mperham.  The repo is transferred.
