### ISSUE TITLE
Deletes partially failing with multi-server setup.

### ISSUE THREAD

**Issue by jeffutter** [petergoldstein/dalli#595]
I am using dalli with a multi-server setup (2 servers).

I seem to be running into an issue where deletes seem to be executed on only one random node. If that node had the key - great, it gets deleted. If the other node had that key, it never gets deleted.

The keys are initially written by the PHP memcache client - perhaps dalli makes some assumptions about what node to execute the delete on? Maybe the memcache client doesn't make the same assumptions when writing the keys?

It is entirely possible I am missing something or doing something wrong here. Any advice? I could open a PR to look into fixing this by making sure delete commands are performed on all servers.

**Comment by jeffutter** [comment]
I have been able to look into this issue more. It seems as though our php implementation is using the 'memcache' library which is fairly dumb about how it sets/gets/deletes keys.
I think on a get it will round robin until it finds the key, and a delete issues a delete on all servers.

It seems as though Dalli is much smarter as can be seen here: https://github.com/petergoldstein/dalli/blob/master/lib/dalli/ring.rb#L32-L38

That bit of code is really incredibly clever and I imagine it balances keys out over the nodes evenly :+1: 

Digging through the C code that php uses for the 'memcached' library, it looks like it does something simliar. Can anyone confirm that Dalli is intended to be compatible with the memcached PHP/C library?

I am wondering if anyone else has looked at compatibility between ruby and PHP implementations of memcached clients. What solutions are out there?

**Comment by jeffutter** [comment]
I believe https://github.com/petergoldstein/dalli/issues/413 could solve my issue.

**Comment by petergoldstein** [comment]
@jeffutter Yes, a PR implementing pluggable hashing would be welcome.
