### ISSUE TITLE
Rails.cache.fetch(key, expires_in: 0.5) doesn't work

### ISSUE THREAD

**Issue by xanview** [petergoldstein/dalli#599]
I have this code:

```ruby
Rails.cache.fetch(key, expires_in: 0.5) do
  true
end
```

I am testing with Rails.cache.exist? cache_key(id) and this key never expires :( -- if I change the expires_in to 1, then it does indeed expires.

Any ideas? -- If this is something memcache doesn't support, maybe Dalli should throw an exception that it's an invalid value?

**Comment by petergoldstein** [comment]
It does work.  `expires_in` should be an integer number of seconds - that's defined in the standard interface for Rails.cache.

Passing it a floating point value will cause the value to be coerced to an integer, in this case `0`.  Try `(0.5).to_i` in the Rails console .  As `0` translates to never expire, this is behaving as expected.

**Comment by xanview** [comment]
Can support for floats be added since memcache supports it?
