### ISSUE TITLE
Please support a floating point expiration time

### ISSUE THREAD

**Issue by xanview** [petergoldstein/dalli#600]
The expires_in standard interface for Rails.cache is supposed to be in seconds, but memcached does not have this limitation. Could support for floating points be added? - e.g. { extended_expires_in: 0.5.seconds }

**Comment by petergoldstein** [comment]
I don't know why you believe this to be the case.  According to the Memcached protocol document, your assertion is false - https://github.com/memcached/memcached/blob/master/doc/protocol.txt .  The TTL is described there as an integer number of seconds.

**Comment by xanview** [comment]
What about this? <

```
lru_crawler sleep <microseconds>

- The number of microseconds to sleep in between each item checked for
  expiration. Smaller numbers will obviously impact the system more.
  A value of "0" disables the sleep, "1000000" (one second) is the max.
```

Why check for an expiration in ms but not support ms for expiration?

**Comment by petergoldstein** [comment]
Again, I dont' understand why you're not reading the plain text:

    Some commands involve a client sending some kind of expiration time
    (relative to an item or to an operation requested by the client) to
    the server. In all such cases, the actual value sent may either be
    Unix time (number of seconds since January 1, 1970, as a 32-bit
    value), or a number of seconds starting from current time. In the
    latter case, this number of seconds may not exceed 60*60*24*30 (number
    of seconds in 30 days); if the number sent by a client is larger than
    that, the server will consider it to be real Unix time value rather
    than an offset from current time.

This clearly refers to an integer number of seconds.

Regarding your comment, it's seems like you're not actually reading the text there either.  Specifically - `microseconds to sleep in between each item checked for expiration`.  That has nothing to do with the size of the TTLs, but rather the behavior of the crawler, which acts like a better garbage collector.  This crawler frees and compactifies the memory, especially in circumstances where slabs may contain a mixture of expired and unexpired items.

**Comment by xanview** [comment]
Ah, I see, ok: https://github.com/memcached/memcached/issues/143
