### ISSUE TITLE
Trim Rails, Ruby support to recent versions

### ISSUE THREAD

**Issue by petergoldstein** [petergoldstein/dalli#602]
As part of the 3.0 release, it would be good to trim the support matrix a bit.

For Rails, I'd like to drop support for Rails 3.x at a minimum - limiting support to Rails 4+.  Ideally we'd drop support for anything older than 4.2.x, but that may be too restrictive.

Similarly, I'd like to trim the Ruby matrix.  Specifically:
- Drop support for Rubinius 2.x
- Drop support for JRuby before JRuby 9000
- Drop support for older MRI versions, potentially all versions prior to 2.2.  A more inclusive set may be appropriate here, but at a minimum I'd like to drop 1.9.3

**Comment by mperham** [comment]
#758
