### ISSUE TITLE
The "socket_max_failures" options doesnot seem to work for write and read operations

### ISSUE THREAD

**Issue by Tholkappiyan** [petergoldstein/dalli#610]
Hi,

  I am using dalli 2.7.0.

  We faced a problem in our production where the memcache instance became unreachable. When a set request was triggered, it should have timed out in 0.5 seconds (the default timeout), instead the dalli client kept retrying.

  On further investigation I found that the failure count is reset on every retry.

  Trace :
1. lib/dalli/server.rb : method write : line 532 - 
     The @sock.write times out.
2. lib/dalli/server.rb : method failure! : line 209 - 
     The @fail_count is incremented
3. lib/dalli/server.rb : method failure! : line 215 - 
     Dalli::NetworkError is raised
4. lib/dalli/client.rb : method perform : line 328 - 
     The transaction is retried
5. lib/dalli/ring.rb : method server_for_key : line 36 - 
     Server's availability is checked.
6. lib/dalli/server.rb : method up! : line 243 - 
     The @fail_count is reset.
   
   The loop continues. Am I missing some config or is there a bug in the dalli code. 
   Can you guys help me figure it out.
   
   The only option that I pass is to compress the serialised data. All the other configs are default values only.

Regards,
Tholkappiyan

**Comment by mrhead** [comment]
@Tholkappiyan did you have any luck figuring this out?

**Comment by Tholkappiyan** [comment]
@mrhead I figured out the issue and fixed the code. https://github.com/petergoldstein/dalli/pull/611. I could not fix the test cases after applying the patch.

**Comment by kofronpi** [comment]
Why was this never fixed/merged ? This seem like a potential annoying problem in prod
