### ISSUE TITLE
Implement `ActiveSupport::Cache::DalliStore#inspect`

### ISSUE THREAD

**Issue by bquorning** [petergoldstein/dalli#617]
Currently, `ActiveSupport::Cache::DalliStore#inspect` is not implemented, and will show…

> the object’s class name, an encoding of the object id, and a list of the instance variables and their values (by calling inspect on each of them).

We are having trouble using the BetterErrors gem in our application, due to the combination of a few things:

 * `DalliStore#inspect` calling `inspect` on all its instance variables,
 * Rails [setting a `@middleware` variable](https://github.com/rails/rails/blob/v4.2.6/activesupport/lib/active_support/cache/strategy/local_cache.rb#L69-L75) on the cache object,
 * Our application doing dependency injection, e.g. `def initialize(cache = Rails.cache); @cache = cache`, and
 * BetterErrors [calling `binding`](https://github.com/charliesome/better_errors/blob/f8aa9afebe559b1148bd30d5a152dafbdd87ac61/lib/better_errors/error_page.rb#L29-L31) on various objects.

I’m not 100% sure where it happens, but the `binding` causes `#inspect` to be called on our `DalliStore` instance, which returns several megabytes that BetterErrors tries to serialize to JSON and … everything kinda stops working.

Would it be ok to implement a `DalliStore#inspect`?

**Comment by petergoldstein** [comment]
So when you say that DalliStore doesn't implement inspect, what you really mean is that DalliStore inherits the verbose version of inspect from somewhere in its parent chain.

Based on the issue you filed, I'm not clear on what you're proposing the method do instead.  The current behavior seems pretty consistent with the intended behavior of inspect.  What would you do differently?

**Comment by bquorning** [comment]
> So when you say that DalliStore doesn't implement inspect, what you really mean is that DalliStore inherits the verbose version of inspect from somewhere in its parent chain.

Yes, `DalliStore#inspect` is inherited from `Object#inspect`.

> Based on the issue you filed, I'm not clear on what you're proposing the method do instead. The current behavior seems pretty consistent with the intended behavior of inspect. What would you do differently?

I’ve worked around it by implementing `#inspect` to return only
```rb
"#<ActiveSupport::Cache::DalliStore>"
```
and it solved my problem with BetterErrors.

On second thought, I’m not sure that this is something Dalli should be concerned with. Perhaps affected applications should just implement this “hack” to work around Rails’ “pollution” of the cache object.

Feel free to close this issue.
