### ISSUE TITLE
[Question] Configure dalli to notify on errors instead of raise

### ISSUE THREAD

**Issue by perobertson** [petergoldstein/dalli#623]
Is it possible to configure Dalli to provide a notification when it fails to connect to the server, and potentially other errors? Right now we have to have filters set up on our logging to notice messages like `DalliError: No server available`.

If we could set the notifier in the config, that would be ideal. Something like this would work.

```
config.cache_store = :dalli_store, '127.0.0.1', { :notify_with => Airbrake }
```

**Comment by btatnall** [comment]
@perobertson I've got a pull request here #645, which will let you use ActiveSupport notifications to hook into whatever other framework you are using. You should be able to subscribe to the ActiveSupport notification and then notify Airbrake.

**Comment by perobertson** [comment]
Excellent. Thanks, it looks like that should do the trick.
