### ISSUE TITLE
Coutermeasures for 'No server availalble'

### ISSUE THREAD

**Issue by nextofsearch** [petergoldstein/dalli#629]
Hi,

We've been suffering the instability of our memcached instances on Memcachier.com. So I am wondering if there is a way to force Rails to skip using dalli and access ActiveRecord when the memcached servers are not available. I will greatly appreciate your help.

Best,

**Comment by petergoldstein** [comment]
@nextofsearch Honestly, I'm not even sure exactly what you're asking.  But if I'm understanding correctly, you can certainly write up a layer that behaves like that if you're using the Rails cache.

But in this situation I'd imagine the better solution is to find a vendor who can provide stable Memcached instances.

**Comment by petergoldstein** [comment]
Closing.
