### ISSUE TITLE
Unexpected exception in Dalli: Timeout::Error: execution expired Exception, - This is a bug in Dalli, please enter an issue in Github if it does not already exist.

### ISSUE THREAD

**Issue by vishnurkrishnan** [petergoldstein/dalli#630]
Yesterday this happened and got so many timeouts, but when i was checking that log i got it like this

35152.943c52.us-east-2.heroku.prod.memcachier.com:11211 failed (count: 0)
- Unexpected exception in Dalli: Timeout::Error: execution expired Exception
- This is a bug in Dalli, please enter an issue in Github if it does not already exist.
- /app/vendor/bundle/ruby/1.9.1/gems/dalli-2.6.2/lib/dalli/server.rb:208:in `sleep'
- 	/app/vendor/bundle/ruby/1.9.1/gems/dalli-2.6.2/lib/dalli/server.rb:208:in `failure!'
- 	/app/vendor/bundle/ruby/1.9.1/gems/dalli-2.6.2/lib/dalli/server.rb:522:in `rescue in read'
- 	/app/vendor/bundle/ruby/1.9.1/gems/dalli-2.6.2/lib/dalli/server.rb:516:in `read'
- 	/app/vendor/bundle/ruby/1.9.1/gems/dalli-2.6.2/lib/dalli/server.rb:458:in `generic_response'
- 	/app/vendor/bundle/ruby/1.9.1/gems/dalli-2.6.2/lib/dalli/server.rb:251:in `get'
- 	/app/vendor/bundle/ruby/1.9.1/gems/dalli-2.6.2/lib/dalli/server.rb:55:in `request'

**Comment by petergoldstein** [comment]
Contrary to the (admittedly confusing) error message, this is not a bug in Dalli.  Your connections timed out, possibly because you overloaded the Memcachier server.

**Comment by vishnurkrishnan** [comment]
ok thanks, also is there any way to find these memcachier server issues, and need to put any configuration changes?

**Comment by petergoldstein** [comment]
Talk to Memcachier support.

**Comment by vishnurkrishnan** [comment]
thanks
