### ISSUE TITLE
Idea: zstd data compression library instead of zlib

### ISSUE THREAD

**Issue by jurgelenas** [petergoldstein/dalli#632]
Facebook recently released a new compression algorithm [Zstandard](http://facebook.github.io/zstd/).

What do you think about swapping zlib with zstd in dalli memcached client?

**Comment by petergoldstein** [comment]
Thanks for the suggestion.

Realistically we're not going to swap the existing default compression for a brand new standard.  That said, if you'd like to create a gem for a compressor that uses this new standard I'd be happy to link to it from a Wiki page
