### ISSUE TITLE
Dalli can indefinitely tries to connect to a server which is not working properly

### ISSUE THREAD

**Issue by mrhead** [petergoldstein/dalli#633]
This happens when server quickly replies to the [version request](https://github.com/petergoldstein/dalli/blob/71746734149cebdd95677dc09f9f60b46582846f/lib/dalli/server.rb#L593) but other operations are slow.

This is not just a theoretical issue and it happens in real world, which was confirmed by folks from Memcachier:

> When you connect to MemCachier, you actually connect to an end-point (aka proxy). All your data is stored on other servers hidden by this endpoint. This is part of what allows us to upgrade or downgrade your cache size in place.
> 
> However, the version command is implemented in the end-point since it doesn't require any dynamic information, while get/set commands need to communicate with a backend server. So if a backend is having problems but not a end-point, then you could see bad behavior.
### The issue

When `dalli` connects to a server and successfully receive reply to a `version` request [then it marks server as up and reset connection failure statistics](https://github.com/petergoldstein/dalli/blob/71746734149cebdd95677dc09f9f60b46582846f/lib/dalli/server.rb#L593-L594).

The issue is that other operations (get/set) can be slow and time out which will cause dalli to retry the connection, receive version from the server, reset connection failure statistics, fail again on next request, etc. This can happen indefinitely.
### The workaround

Set `socket_max_failures` to `1` (default value is `2`) to never retry failed connections and instead mark as down for `down_retry_delay` seconds.

I also recommend to set `down_retry_delay` to a higher value (default is `1`, see also https://github.com/petergoldstein/dalli/issues/621).
### How to reproduce

Follow the instructions in: https://github.com/mrhead/dalli-connection-issues
### The solution

I am not sure.

Maybe we should reset connection failure statistics in some other place then `Dalli::Server#connect`.

**Comment by mrhead** [comment]
I just found https://github.com/petergoldstein/dalli/issues/610 which looks related.

**Comment by mrhead** [comment]
@petergoldstein I've dug deeper and I found a root cause of this issue. I've also created a simple script how to reproduce this issue.

However, I am not sure about possible solution and I am not sure if this should be fixed in the gem directly.

**Comment by petergoldstein** [comment]
@mrhead Sorry it's taken me so long to look at this issue.

At the end of the day, this seems like a consequence of Memcachier's architecture.  They've made a choice to split the Memcached API between two different systems, and are not taking responsibility for ensuring consistent behavior across both systems.  That doesn't seem like an issue a generic Memcached library should be responsible for accommodating.

With that in mind I'm going to close this issue.

**Comment by mrhead** [comment]
> @mrhead Sorry it's taken me so long to look at this issue.

It's okay!

> That doesn't seem like an issue a generic Memcached library should be responsible for accommodating.

In the hindsight I agree. I was just too excited when I finally figured out what was going on, so I've opened this issue. Also, the workaround which I mentioned is working well, and we did not have a single issue since I've implemented it.
