### ISSUE TITLE
Weird exception in active_support/cache/dalli_store.rb

### ISSUE THREAD

**Issue by gee-forr** [petergoldstein/dalli#644]
Hi and happy new year to  you all :)

I've got a weird problem, where I'm unable to cache a particular item... I'm getting the following error:

```
NoMethodError: undefined method `>' for false:FalseClass
from /home/app/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/dalli-2.7.6/lib/active_support/cache/dalli_store.rb:105:in `=='
```

Here's the code:

```ruby
def average_duration(vspot, venue, from, to)
  cache.fetch(caching_key, expires_in: expire_time) do
    cache_missed_message

    get_average_duration(vspot, venue, from, to)
  end
end
```

And here's what some of the values are:

```ruby
[1] pry(#<Widgets::SpotAverageVisitDurationV1>)> caching_key
=> "spot_average_visit_duration_v1_70_7-days"
[2] pry(#<Widgets::SpotAverageVisitDurationV1>)> expire_time
=> 259200 seconds
```

I've searched all over the issues list, and can't find anything similar... also, when I inspect the code that is apparently breaking, i.e. [line 105 in dalli_store.rb](https://github.com/petergoldstein/dalli/blob/master/lib/active_support/cache/dalli_store.rb#L106) it's happening within the `#fetch` method and not a `#==` method.

Any help would be greatly appreciated, and I'm happy to share as much as needed in order to fix this possible bug.

Thanks guys, really appreciate this gem and the hard work you've put into it, it's been amazing working with it over the years.

**Comment by gee-forr** [comment]
Huh... that's weird...

When I change the caching_key value to `spot_average_visit_duration_v1_70_7-day` (chop off the trailing 's') or `spot_average_visit_duration_v1_70_7-daysx` (add a trailing 'x'), it works fine.

It's clear there's something Dalli doesn't like about that key...

**Comment by gee-forr** [comment]
OK, I've dug a little deeper, and I can confirm that if it's a brand new key, it will happily cache away. It's only when it attempts to fetch a previously cached key that it will trigger this exception.

**Comment by petergoldstein** [comment]
@gee-forr What's the class of the key?  Is it a string, a SpotAverageVisitDurationV1, or something else?

My suspicion is that you may be using a complex class for the caching key that doesn't support '=='.  ('!=' on line 105 is probably implemented under the covers using '==', which is why it's reporting a problem with '==')

**Comment by gee-forr** [comment]
hey @petergoldstein...

Unfortunately, it's a standard string, here's my implementation:

```ruby
    def caching_key
      "#{class_key_name}_#{context.product_instance_id}_#{report_interval_identifier}"
    end
```

**Comment by petergoldstein** [comment]
@gee-forr What's the class of the value?  If you instantiate such a value in console, does it behave as expected under equality comparisons?

**Comment by gee-forr** [comment]
Hi @petergoldstein,

`caching_key` is simply a string... see below:

```
[2] pry(#<Widgets::SpotAverageVisitDurationV1>)> caching_key
=> "spot_average_visit_duration_v1_6_about-6-hours"
[3] pry(#<Widgets::SpotAverageVisitDurationV1>)> caching_key.class
=> String
[4] pry(#<Widgets::SpotAverageVisitDurationV1>)> dup_key = caching_key.dup
=> "spot_average_visit_duration_v1_6_about-6-hours"
[5] pry(#<Widgets::SpotAverageVisitDurationV1>)> dup_key.object_id
=> 70158800932440
[6] pry(#<Widgets::SpotAverageVisitDurationV1>)> caching_key.object_id
=> 70158844603800
[7] pry(#<Widgets::SpotAverageVisitDurationV1>)> dup_key == caching_key
=> true
[8] pry(#<Widgets::SpotAverageVisitDurationV1>)> dup_key != caching_key
=> false
```

Hope this helps... if there's anything else I can do to shed some light, let me know :) In the meantime, I've disabled caching for this particular piece of code...

**Comment by petergoldstein** [comment]
@gee-forr I wasn't asking about the caching key - I was asking about the corresponding cached value.

**Comment by gee-forr** [comment]
Hi @petergoldstein, apologies, misunderstood you there :)

It's a Duration object: #<Duration:0x007fefd4e33318 @seconds=0, @negative=false, @total=3300, @weeks=(11/2016), @days=(11/288), @hours=(11/12), @minutes=55> from https://github.com/peleteiro/ruby-duration

That's probably the issue. I'm going to patch that method, and see if I can cache it as something a little more primitive, like a Hash instead.

Thanks for your time and attention, I really appreciate it.
