### ISSUE TITLE
Using an external memcached server

### ISSUE THREAD

**Issue by mjdavies** [petergoldstein/dalli#648]
Hi everyone

Probably doing something really stupid.

Running with docker

rails 4.2.1
dalli 2.7.6

production.rb entry

config.cache_store = :dalli_store, 'DOCKER_CONTAINER_NAME:11211',{ :namespace => 'fox', :compress => true }

The containers are linked

I can't seem to set the external container/servername, it's always saying can't connect to 127.0.0.1

127.0.0.1:11211 failed (count: 0) Errno::ECONNREFUSED: Connection refused - send

Anybody see my stupid?

**Comment by mjdavies** [comment]
I got it

If I pass in and ENV of cache_HOST in the docker-compose file, then refer to that in the line

config.cache_store = :dalli_store, ENV["CACHE_HOST"],{ :namespace => 'fox', :compress => true }

That works

No idea why

**Comment by mecjack** [comment]
@mjdavies Thank you so much, saved my day!!!
