### ISSUE TITLE
locale cache + unless_exist = ArgumentError

### ISSUE THREAD

**Issue by grosser** [petergoldstein/dalli#655]
```
/gems/activesupport-5.1.0/lib/active_support/cache/strategy/local_cache.rb:47 in clear
/gems/activesupport-5.1.0/lib/active_support/cache/strategy/local_cache.rb:90 in cleanup
/gems/dalli-2.7.6/lib/active_support/cache/dalli_store.rb:310 in write_entry
/gems/activesupport-5.1.0/lib/active_support/cache/strategy/local_cache.rb:119 in write_entry
```

 - dalli calls cleanup (idk why ... seems weird that it clears the whole local cache ...)
 - cleanup does not accept options
 - 💥 

the error is not really dallis fault, but it might want to not call cleanup since that clears the local cache and seems a bit excessive ... https://github.com/rails/rails/issues/29067

**Comment by eugeneius** [comment]
The call to `cleanup` was added in https://github.com/petergoldstein/dalli/pull/365. If the `unless_exist` option is passed, we don't know what the final value in the backend cache is, so to be safe we dump the entire local cache. There's a test in that pull request that requires this behaviour to pass.

I think we can fix the problem in Rails instead though: https://github.com/rails/rails/pull/29083

**Comment by grosser** [comment]
I'll close this ... seems like a straight forward rails bug ...
