### ISSUE TITLE
When using multiple memcache servers what is dalli's strategy?

### ISSUE THREAD

**Issue by arianf** [petergoldstein/dalli#656]
I'm experiencing a weird issue. I'm currently using dalli (2.6.4)

I store my sessions in memcache with the dalli gem.

However, sometimes when a session is stored, the next request can't find the session, but the following requests after that can find it.

I am using 3 memcache servers. I was wondering how dalli or memcache distribute data between different memcache servers?

Seems like the issue could be one instance of rails is writing to server 1, and another instance is reading from server 2?

Does dalli/memcached shard?

**Comment by reneklacan** [comment]
@arianf you can just check the Dalli's code for your answer https://github.com/petergoldstein/dalli/blob/master/lib/dalli/ring.rb#L31

**Comment by petergoldstein** [comment]
Closing, since this is described in code/documentation.
