### ISSUE TITLE
incr on numeric keys throws an exception

### ISSUE THREAD

**Issue by redterror** [petergoldstein/dalli#66]
It seems if you #set a key to a numeric value and then try to incr/decr it, we get an exception from the server.  In this example, 'c' is a connected Dalli::Client object:

ruby-1.9.2-p136 :006 > c.set("foo", 0)
 => true
ruby-1.9.2-p136 :007 > c.get("foo")
 => 0
ruby-1.9.2-p136 :008 > c.incr("foo")
Dalli::DalliError: Response error 6: Incr/decr on a non-numeric value
        from /usr/local/rvm/gems/ruby-1.9.2-p136@nvid/gems/dalli-1.0.1/lib/dalli/server.rb:313:in `generic_response'
        from /usr/local/rvm/gems/ruby-1.9.2-p136@nvid/gems/dalli-1.0.1/lib/dalli/server.rb:202:in`incr'
        from /usr/local/rvm/gems/ruby-1.9.2-p136@nvid/gems/dalli-1.0.1/lib/dalli/server.rb:43:in `request'
        from /usr/local/rvm/gems/ruby-1.9.2-p136@nvid/gems/dalli-1.0.1/lib/dalli/options.rb:14:in`block in request'
        from /usr/local/rvm/rubies/ruby-1.9.2-p136/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
        from /usr/local/rvm/gems/ruby-1.9.2-p136@nvid/gems/dalli-1.0.1/lib/dalli/options.rb:13:in`request'
        from /usr/local/rvm/gems/ruby-1.9.2-p136@nvid/gems/dalli-1.0.1/lib/dalli/client.rb:225:in `perform'
        from /usr/local/rvm/gems/ruby-1.9.2-p136@nvid/gems/dalli-1.0.1/lib/dalli/client.rb:163:in`incr'
        from (irb):8
        from /usr/local/rvm/rubies/ruby-1.9.2-p136/bin/irb:17:in `<main>'

This is fairly easily worked around as:

c.remove("foo") ; c.incr("foo", 1, nil, 0)

But it seems like the set/incr combo ought to work, no?  This is on dalli 1.0.1.

**Comment by hirschnase** [comment]
@mperham can you please please add this to the documentation? I stumbled upon the exact the problem and was not able to solve this by my-self by reading the spec/doc. This should be documented as part of the incr/decr methods. Thank you!
