### ISSUE TITLE
DalliError: Response error 130: Out of memory

### ISSUE THREAD

**Issue by tstone** [petergoldstein/dalli#660]
When using Dalli with Rails, we've been seeing an issue where one or more hosts will receive a `DalliError: Response error 130: Out of memory` on a particular process.  Soon thereafter subsequent memcache get's (Rails.cache.fetch) appear to return out of order, resulting in many `NoMethodError` and `ArgumentError` as methods are given instances of classes they are not expecting.  The errors are isolated to only the process that received the 130: Out of memory.  All other processes continue to operate as expected.  Restarting passenger/nginx eliminates the errors, since the offending process is killed/restarted.

**Stack:**
* ElasticCache - Memcached 1.4.34
* kgio 2.11.0
* Dalli 2.7.6
* Rails 4.2.8
* Passenger 5.1.4
* Ruby 2.4.1
* nginx 1.10.3

**Comment by onyxraven** [comment]
It looks like the dalli client currently eats any error details for the various status errors 
in /lib/dalli/server.rb#L505, and throws an exception. At least with a lot of the OOM errors, there should be a more specific error message in the data payload of the response from the memcached server.  

This may be related to the out of order key/values seen after receiving the OOM message from our investigation so far.
