### ISSUE TITLE
Dalli max value handling doesn't account for memcached 'actual' max value

### ISSUE THREAD

**Issue by patrickbsf** [petergoldstein/dalli#668]
With Dalli 2.7.6, talking to Memcached 1.4.14, if I write a simple test like:
`
max = 1024*1024
(max-128..max).each do |size|
  connection.set("largevalue", "x" * size, 0)
end
`
Then it will be fine except for 'size' 1,048,483 - 1,048,563 - raising the "Response error 3: Value too large" exception.  For the simple "x" * size value - that gets marshaled - adding 13 bytes to size.
From size 1,048,564 and on it logs the 'Value for xxx over max size: x <= y' message and 'set' correctly returns false.  It should return false for all of these values, never raising the value too large exception.
So Dalli isn't actually accounting for the additional bytes that Dalli's driver, the protocol, or memcached itself adds after comparing against the 1M / 1,048,576 'max'.

**Comment by patrickbsf** [comment]
It looks like the problem is worse than just the value size.  The max size in memcache is actually the size of the key and value + some implementation specific data, yet dalli is only guarding against a max value (and not accounting for extra bytes in marshal).
It wouldn't be to the byte accurate (it definitely isn't now) but creating the 'req' packed string and then checking its size in guard_max_value would be more accurate.

**Comment by vadimeremeev** [comment]
+1

**Comment by petergoldstein** [comment]
I'd be happy to take a PR that addresses the issue.
