### ISSUE TITLE
ActionView::Template::Error (nil can't be coerced into Integer):

### ISSUE THREAD

**Issue by Ladas** [petergoldstein/dalli#678]
Caused by Dalli  2.7.7

2.7.7 uses:
https://github.com/rack/rack/blob/b37356ee881c0de4266165dacb8af4efaebaf4ec/lib/rack/session/abstract/id.rb#L254

But 2.7.6 uses:
https://github.com/rails/rails/blob/2d2da1861576a3900a295dc3950b447027f9ed9d/actionpack/lib/action_dispatch/middleware/session/abstract_store.rb#L26

----

https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/middleware/session/abstract_store.rb#L26 fails on @sid_length being nil, because we nullify the :sidbits here https://github.com/rails/rails/blob/2d2da1861576a3900a295dc3950b447027f9ed9d/actionpack/lib/action_dispatch/middleware/session/abstract_store.rb#L35

-----

most likely this is caused by last 2 commits in https://github.com/petergoldstein/dalli/commits/v2.7.7/lib/rack/session/dalli.rb

**Comment by himdel** [comment]
The error happens when trying to generate a new session id - already logged in sessions keep working, so restarting/clearing memcached may be needed to trigger this error.

**Comment by petergoldstein** [comment]
@Ladas  So as is, this isn't an actionable bug report.  Can you please provide some more information?  Some things that would be helpful:

1. In what context are you observing this error?
2. With what versions of Rack (and Rails, etc.) are you seeing this error?
3. Why isn't this a Rails bug?  Is Dalli calling a method improperly, or not implementing a required method?  Why doesn't generate_sid work as Dalli expects?  Why is the sidbits value being cleared at all?

Thanks.

**Comment by Ladas** [comment]
@petergoldstein 

1) running ```rails s``` there is the <subject> exception when trying to touch the session
2) rails 5.0.2, rack 2.0.4
3) the last 2 commits added in https://github.com/petergoldstein/dalli/commits/v2.7.7/lib/rack/session/dalli.rb are changing what methods are called. 

so in 2.7.6 were calling https://github.com/rails/rails/blob/2d2da1861576a3900a295dc3950b447027f9ed9d/actionpack/lib/action_dispatch/middleware/session/abstract_store.rb#L26 , 2.7.7 is calling https://github.com/rack/rack/blob/b37356ee881c0de4266165dacb8af4efaebaf4ec/lib/rack/session/abstract/id.rb#L254 

I am not sure if it's a Rails bug or not, it looks weird that the Compatibility module is always overwriting methods from Persisted class. 

Our fix for now is to revert to dalli to 2.7.6. It might be that the root of the failure is that there shouldn't be any Compatibility module overwriting behavior like this. 

I haven't checked in detail why dalli uses different method now, but I've identified it's caused by the last 2 commits added in https://github.com/petergoldstein/dalli/commits/v2.7.7/lib/rack/session/dalli.rb

-----

Why do we call https://github.com/rails/rails/blob/2d2da1861576a3900a295dc3950b447027f9ed9d/actionpack/lib/action_dispatch/middleware/session/abstract_store.rb#L34 in both 2.7.6 and 2.7.7? I have no idea. :-) The whole Compatibility module just looks wrong. As for why is cleaning of the :sidbits needed, there is a verbose ```# :doc:``` :-D

-----

It looks to me correct way should be using:
https://github.com/rack/rack/blob/b37356ee881c0de4266165dacb8af4efaebaf4ec/lib/rack/session/abstract/id.rb#L244
and
https://github.com/rack/rack/blob/b37356ee881c0de4266165dacb8af4efaebaf4ec/lib/rack/session/abstract/id.rb#L254

But by including of the Compatibility module, we overwrite both of these methods:
https://github.com/rails/rails/blob/2d2da1861576a3900a295dc3950b447027f9ed9d/actionpack/lib/action_dispatch/middleware/session/mem_cache_store.rb#L18

For some reason ```:generate_sid``` stops being overwritten in dalli 2.7.7

**Comment by petergoldstein** [comment]
@Ladas Can you please test Dalli master and see if you still have the same issue?  If it's fixed I can release 2.7.8.  Thanks.

**Comment by tomhughes** [comment]
I can confirm that applying 9ad5ccac463f852df42d2bd66104b767366974e2 to 2.7.7 fixes this for me.

**Comment by Ladas** [comment]
@petergoldstein I believe that guys from our office tested this works, so we can close this issue. Thanks
