### ISSUE TITLE
Confusion about rails 5.2 cache versioning

### ISSUE THREAD

**Issue by Aqualon** [petergoldstein/dalli#710]
Hello, I just saw in the history "Fix behavior for Rails 5.2+ cache_versioning" introduced by https://github.com/petergoldstein/dalli/pull/698. There support was added to check `cache_key_with_version` which is also used in https://github.com/rails/rails/blob/276fa9dd3cdd567a0a9d93ac6a001709896c7c47/activesupport/lib/active_support/cache.rb#L94

On the other hand I see calls to `cache_version` in https://github.com/rails/rails/blob/276fa9dd3cdd567a0a9d93ac6a001709896c7c47/activesupport/lib/active_support/cache.rb#L652

Trying out the example from @schneems in https://github.com/rails/rails/issues/33907 I still see the problem different behavior between dalli 2.7.9 and rails memory_store

```
ModelWithKeyAndVersion = Struct.new(:cache_key, :cache_version)
model_1_cache_1 = ModelWithKeyAndVersion.new("model/1", "1")
model_1_cache_2 = ModelWithKeyAndVersion.new("model/1", "2")

Rails.cache.fetch(model_1_cache_1) { "woohoo" }
Rails.cache.read(model_1_cache_1) # => "woohoo"
```
```
Rails.cache.read(model_1_cache_2) # => "woohoo" for dalli
Rails.cache.read(model_1_cache_2) # => nil for memory_store
```

Since I barely know anything about rails caching internals I wonder, if there is still a bug in dalli or if this different behavior is explainable?

**Comment by schneems** [comment]
It's tough to say, I don't think the `cache_key_with_version` is really well documented from the Rails side of things, i.e. if you have a custom (non-AR object) that you want to put in the cache then you'll need to know about this method (in addition to `cache_key` and `cache_version`). Depending on where you use the object you might need to implement this method no matter what cache store you are using. In that regards it's technically an implementation bug in my example.

That answer feels harsh though. I'm not sure exactly where I would claim the bug to be. One answer could be to abandon the dalli_store all together and instead have people use the `mem_cache_store` from Rails. I don't know if there are other benefits to maintaining a separate cache store backend.
