### ISSUE TITLE
Print all key values using dalli

### ISSUE THREAD

**Issue by ndvbd** [petergoldstein/dalli#713]
How to iterate and print all keys/values using dalli?

**Comment by bf4** [comment]
@ndvbd Do you know how to do it with memcached?

You can't really. I you can get the stats for slabs and then try using cachedump.. but dalli isn't really the right tool for that.

**Comment by fffx** [comment]
@ndvbd  Check https://stackoverflow.com/questions/19560150/get-all-keys-set-in-memcached

**Comment by petergoldstein** [comment]
As noted in the comments, this isn't really something that is suitable for Dalli.  There are other mechanisms for doing this, but they don't use the Memcached API that Dalli fronts.
