### ISSUE TITLE
Always show the namespace when globally set

### ISSUE THREAD

**Issue by dennym** [petergoldstein/dalli#714]
When using namespace like this it shows the namespace and can make sure keys are not used cross application.

```
Rails.cache.fetch('foo', namespace: 'bar') { User.last }
Cache read: bar:foo ({:namespace=>"bar"})
Cache fetch_hit: bar:foo ({:namespace=>"bar"})
```

When using namespace via the dalli config it doesn't show the namespace.
```
dalli_config =  {:hosts=>["127.0.0.1:11211"], :namespace=>"development" } 
config.cache_store = :dalli_store, dalli_config['hosts'], dalli_config
Rails.cache.fetch('foo') { User.last }
Cache read: foo
Cache fetch_hit: foo
```
This is problematic since I couldn't see if the namespace is utilized. Issue was that I load the memcached config options from a yaml file and hat to `.deep_symbolize_keys`. 

To debug this issue and the only way of actually testing it is doing manual fetches on the same key with different payloads on different enviroments to see any difference. 
`Rails.cache.stats['127.0.0.1:11211']['curr_items']` also didn't help since it seems to show just the memcached stats and these don't use namespace and returns the count of all cached keys.

**Comment by siddharth1001** [comment]
Is this a valid request ? Should we add an option to always log the namespace if such an option is given to Dalli class ?
