### ISSUE TITLE
InvalidAuthenticityToken

### ISSUE THREAD

**Issue by philsmy** [petergoldstein/dalli#73]
This is quite strange. We have one test client computer - a Windows 64 bit machine - that cannot log in using any browser! (IE, FF, Chrome). We are getting ActionController::InvalidAuthenticityToken.

Our session_store looks like this:

  MyApp::Application.config.session_store :dalli_store, 
          :memcache_server => ['xx'], 
          :namespace => 'sessions', 
          :key => '_myapp_r3_session', :expire_after => 30.minutes

If I remove Dalli, and just use:

  MyApp::Application.config.session_store :cookie_store, :key => '_xxx-xxx-devise_session', :domain => :all

We can log in without issue.

The login page is not cached. I can see it is submitting a different authenticity token each time.

What can we do to debug this further and resolve this? For now we have had to switch off dalli

environment is Rails 3 and yes we are using Devise

**Comment by dheenaINDIAN** [comment]
i have configured dalli gem version 2.7.4
added, Rails.application.config.session_store  ActionDispatch::Session::CacheStore, :expire_after => 5.minutes, :domain => :all, tld_length: 2

Once the user logged in and  session expires(20 seconds got  over), i am receiving the below issue 

ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken)

After that i cant able to login again. always it throws the same error.
