### ISSUE TITLE
Missing cache key expansion for single item array keys

### ISSUE THREAD

**Issue by cmaion** [petergoldstein/dalli#733]
Hi,

Caching using a single item array as the key doesn't properly uses the cache_key method, but calls to_param only.

Eg:

- `[ model1, model2 ]` is properly expanded to `[model1.cache_key, model2.cache_key].to_param`.
- `model1` is properly expanded to `model1.cache_key`.
- `[ model1 ]` is expanded to `model1.to_param` (instead of `model1.cache_key`).

See:
https://github.com/petergoldstein/dalli/blob/8b19276d27d29b7b3abb6e3aab48ce054d165619/lib/active_support/cache/dalli_store.rb#L357-L372

(line 364 vs 366)

**Comment by mperham** [comment]
Send a PR.
