### ISSUE TITLE
Dalli should handle hostnames which map to more than one IP address

### ISSUE THREAD

**Issue by dgholz** [petergoldstein/dalli#740]
I noticed that the TCP server connects by calling `Socket.pack_sockaddr_in` with the user-supplied host name.
https://github.com/petergoldstein/dalli/blob/96da6efdfc3ec634583976351909e9a63bb456c2/lib/dalli/socket.rb#L60
`pack_sockaddr_in` only returns a single packed address, so if the name has more than one address (i.e. it's a round-robin record or dual-stack IPv4/IPv6), the user might be surprised if the address they expected wasn't used.

I think Dalli should notice when the user passed an ambiguous hostname and warn about it. It would be nice if Dalli expanded hostnames to addresses and created a server connection for each & added them to the ring, or if it used `Socket.getaddrinfo` and let the user pass which address family they'd prefer in the config.

I believe this is the cause of #324, where Dalli tried to connect to the first entry returned for `localhost` (either `127.0.0.1` or `::1`), but `memcached` was only connectable on the other one.

**Comment by mperham** [comment]
Send a PR.
