### ISSUE TITLE
text protocol and meta command support

### ISSUE THREAD

**Issue by shivnagarajan** [petergoldstein/dalli#741]
With the addition of the new [metacommands](https://github.com/memcached/memcached/wiki/MetaCommands) to memcached (available in the text protocol), would there be interest to support the text protocol with dalli? (and supporting the meta commands with it also).

Addition of text protocol support would also allow the use of dalli with proxies like [mcrouter](https://github.com/facebook/mcrouter).

Are there any caveats/issues to be concerned about in adding this support. 

We use dalli, (in some cases), text protocol  (in many cases) mcrouter and currently are working towards using the meta commands. As it stands our applications that use dalli cannot use mcrouter, and applications that use text protocol (and mcrouter) cannot use dalli, and these clients will soon be adding the use of the meta commands also.

@ndurks @dormando

**Comment by dormando** [comment]
I wonder if it makes sense for this to be done with dalli, since that was always a binprot-first client. You might have better luck with a compatibility wrapper over something really minimalist/simple.

**Comment by mperham** [comment]
Dalli is in long-term maint mode, we don't have a maintainer that can spend a lot of time on major overhauls. You can fork Dalli or you can step up if you have a vision for 3.0 and are willing to do the work.

**Comment by byroot** [comment]
> are willing to do the work

Of course. I'll submit a few PRs soonish. Also I've seen https://github.com/petergoldstein/dalli/issues/758, I can help with that TODO list.
