### ISSUE TITLE
DalliStore#log_dalli_error() does not suppress logs using @silence 

### ISSUE THREAD

**Issue by masago** [petergoldstein/dalli#742]
`DalliError` rescued in `DalliStore` methods is often logged using  `#log_dalli_error` method.  It only logs if logger exists. However, it does not suppress the log when `@silence` is set using `#silence!` or `#mute`.  It would be helpful to honor `@silence`.

**Comment by BrandonMathis** [comment]
I would like to follow-up on this. Documentation and googling indicates that `Rails.cache.silence` will silence dalli logs but that doesn't seem to work. Neither does `Rails.cache.mute`

Temporary solution that I use to silence cache fetches in my logs is

```ruby
Rails.cache.silence do
  Rails.cache.fetch("some-cache-key") do
    # ...
  end
end
```

**Comment by mperham** [comment]
Send a PR.
