### ISSUE TITLE
Please cut a new version

### ISSUE THREAD

**Issue by johnnyshields** [petergoldstein/dalli#753]
It's been over a year since last release and master has critical fixes that are unreleased.

**Comment by johnnyshields** [comment]
@petergoldstein

**Comment by mperham** [comment]
Hey @petergoldstein, would you be ok with me taking over as maintainer for a few weeks? Here's my initial plan:

* release 2.7.11 based on master
* create a 3.0 branch
* merge a bunch of the easy pending PRs and issues into 3.0
* remove old ruby and rails support
* upgrade IO in socket.rb to latest modern APIs, remove kgio
* remove travis CI, add github action CI with live memcached
* release 3.0

**Comment by petergoldstein** [comment]
@mperham Yes, I'm good with that.  Would appreciate it - I haven't had time to devote to Dalli in a while, and I haven't seen much engagement from contributors.

**Comment by mperham** [comment]
2.7.11 is now out which deprecates :dalli_store.

**Comment by johnnyshields** [comment]
Awesome, thanks!
