### ISSUE TITLE
read_multi does not retry on NetworkError

### ISSUE THREAD

**Issue by ccoffey** [petergoldstein/dalli#755]
`cache.read` automatically retries on `NetworkError` but `cache.read_multi` does not. This is an unexpected difference.

The below results were generated by running the server as follows:
`memcached -o idle_timeout=2`

The following setup was also run:

```ruby
test_memcache_store = 'localhost:11211'

test_memcache_settings = {
  expires_in: 3.days,
  failover: false,
  socket_timeout: 5,
  down_retry_delay: 0,
  socket_max_failures: 5,
  compress: true,
  pool_size: 30,
  pool_timeout: 5,
  value_max_bytes: 104857600,
  instrument_errors: true,
}

test_store = :dalli_cas_store, test_memcache_store, test_memcache_settings

cache = ActiveSupport::Cache.lookup_store(test_store)

# Fill the cache with 10 values
(1..10).each { |i| cache.write(i.to_s, "value#{i}") }
```

`cache.read` retry behaviour:

```ruby
# Wait for 5 seconds so that the open connection becomes idle and is closed by the server
cache.read("1")
Cache read: 1
localhost:11211 failed (count: 0) EOFError: end of file reached
#<Dalli::NetworkError: Socket operation failed, retrying...>
retrying request with new server
Dalli::Server#connect localhost:11211
=> "value1"
```

`cache.multi_read` no retry behaviour:

```ruby
# Wait for 5 seconds so that the open connection becomes idle and is closed by the server
cache.read_multi("1")
Cache read_multi: ["1"]
localhost:11211 failed (count: 0) EOFError: end of stream
=> {}
```

**Comment by ccoffey** [comment]
Here is a WIP PR that fixes this: https://github.com/petergoldstein/dalli/pull/754, the tests are passing locally but not in CI. Any guidance would be appreciated!

**Comment by ccoffey** [comment]
@mperham why was this closed with no comment? Do you not think this is a problem worth fixing? Have I misunderstood the issue somehow?

**Comment by mperham** [comment]
Because #754 exists. There’s no reason for pool to be open

**Comment by ccoffey** [comment]
Thank you @mperham. Any feedback to help get https://github.com/petergoldstein/dalli/pull/754 over the line? I have some specs that fail in CI but pass locally which makes is making it difficult to debug.

**Comment by mperham** [comment]
We are removing dalli_store so I’d recommend you spend your time getting the official :mem_cache_store working instead.
