### ISSUE TITLE
Timeouts

### ISSUE THREAD

**Issue by vitobotta** [petergoldstein/dalli#763]
Hi! I migrated my cluster to DigitalOcean Kubernetes today and for some reason I am seeing frequent timeout errors when Rails connects to the memcached instances. I suspect it's some networking configuration in DO that may cause some delay or something, not sure. So I am trying to tweak the settings with dalli but I am not sure of which values to specify. At the moment I have:

```ruby
config.cache_store = :mem_cache_store, *(Settings.memcache_servers.split(",") + [{ namespace: Settings.kube_namespace, pool_size: 5, socket_timeout: 2, socket_max_failures: 3, socket_failure_delay: 0.05, down_retry_delay: 5 }])
```

Is there a way I can troubleshoot and find out what is causing these timeouts? I don't have any other problems with all the stuff in the cluster. The app works fine and I am self hosting a Postgres cluster in there as well. Thanks a lot in advance for any suggestions.

**Comment by petergoldstein** [comment]
@vitobotta Apologies for the slow reply.

At this point all the Dalli client options are documented here - https://github.com/petergoldstein/dalli/wiki/Dalli::Client-Options .  Other than recommending that you tune values based on the documentation, I can't give you much troubleshooting advice based on the above.  Hopefully this is a resolved issue for you by now.
