### ISSUE TITLE
`session[:session_id]` return undefined method `public_id' with Rails 5.2

### ISSUE THREAD

**Issue by GCorbel** [petergoldstein/dalli#765]
I'm upgrading an application from Rails 5.1 to Rails 5.2. When I do `session[:session_id]`, it gives the error `undefined method 'public_id'` because of a change introduced in [this commit](https://github.com/rails/rails/commit/92ec9f270d696a17ba7604b3d02931f07c3e7c6a). `session[:session_id]` is doing `session.id.public_id` [internally](https://github.com/rails/rails/blame/5699122abf7613465c62f2e50e3af017e95cb609/actionpack/lib/action_dispatch/request/session.rb#L95-L99). It works correctly with `ActionDispatch::Session::CookieStore` because, in this case, `session.id` returns a [Rack::Session::SessionId](https://github.com/rack/rack/blob/2.1.4/lib/rack/session/abstract/id.rb) which implement `public_id`.

`session.id` should probably return and object that implement the same methods as `Rack::Session::SessionId`.

**Comment by GCorbel** [comment]
My bad, I tried with the master branch and `session.id` correctly returns a `Rack::Session::SessionId`. Thanks.

**Comment by GCorbel** [comment]
I

**Comment by rafaelfranca** [comment]
I'd not say a full rewrite but it need to be made compatible. A few methods will need to change for sure to know about ` Rack::Session::SessionId` objects.
