### ISSUE TITLE
Undefined method error with when reading the cache with Rails 5.2.

### ISSUE THREAD

**Issue by GCorbel** [petergoldstein/dalli#766]
I'm running an application with Rails 5.2.4 and Dalli on the master branch. 

`Rails.application.config.cache_store` is returning : 

```
[:mem_cache_store,
 "memcache",
 {:namespace=>"cache:application:development:v2",
  :expires_in=>1 hour,
  :compress=>true}]
```

When I do 

```
Rails.cache.read('test')
```
NoMethodError: undefined method 'with' is raised.

This is because the method `with` has been removed in [this commit](https://github.com/petergoldstein/dalli/commit/c6fc3101bdbf00357f649f2ddd0cf93fe50f060a) but it still used in [ActiveSupport::Cache::MemCacheStore](https://github.com/rails/rails/blob/v5.2.4.4/activesupport/lib/active_support/cache/mem_cache_store.rb#L132).

The method `with` is required until `MemCacheStore` is fixed for compatibility issue.

**Comment by petergoldstein** [comment]
@ryanb @GCorbel  I put in a PR that I believe resolves this issue.  If you have a minute to run a test locally against the master branch and confirm, that would be helpful.  I expect to release a new gem version tonight.

**Comment by ryanb** [comment]
I don't have time to test tonight but will tomorrow. Feel free to release if you want. Thanks @petergoldstein!

**Comment by ryanb** [comment]
For the record, this works for me too. Thanks!
