### ISSUE TITLE
undefined method `dup_value!' with dalli 2.7.11 and rails 6.1

### ISSUE THREAD

**Issue by roccoblues** [petergoldstein/dalli#771]
A simple `Rails.cache.write` with `:dalli_store` and Rails 6.1 leads to `undefined method `dup_value!'`.

I tracked it down to this commit in rails: https://github.com/rails/rails/commit/9b09187650e3f5a196f38142ccddcfd4ec365862#diff-ec46f57f15b817f91efebde97d0e74edfc656ada553296cecdf09a9611d95bf5

There was also an issue opened in rails reporting the same problem: https://github.com/rails/rails/issues/40869

Is dalli 2.x supposed to support rails 6.1?

**Comment by petergoldstein** [comment]
@roccoblues  So Dalli 2.x wasn't validated against Rails 6.1.  Is there a reason you don't want to use MemCacheStore?

**Comment by roccoblues** [comment]
Hi @petergoldstein, we're using an internal gem that builds on DalliStore. We tried to switch that to MemCacheStore but had to rollback due to a huge increase (allocated bytes doubled) in allocations when we switched. We haven't investigated further but the theory is that that comes from the fact that MemCacheStore wraps every cache data into an additional `ActiveSupport::Cache::Entry` object.

**Comment by ssherman** [comment]
I am having this same problem. Switching to the mem_cache_store in the mean time.

**Comment by qrush** [comment]
Also running into this during a Rails 6.1 upgrade and didn't discover it until we got it out on our staging server.

@petergoldstein should there be a 2.7.12 released that is pinned to Rails < 6.1 ? And then maybe 2.8 can introduce 6.1 compat?

Relative stack trace here, coming from a `Rails.cache.fetch` block:

```
vendor/bundle/ruby/2.6.0/bundler/gems/rails-9f39d00ed29f/activesupport/lib/active_support/cache/strategy/local_cache.rb:68:in `write_entry': undefined method `dup_value!' for false:FalseClass (NoMethodError)
    from vendor/bundle/ruby/2.6.0/bundler/gems/rails-9f39d00ed29f/activesupport/lib/active_support/cache/strategy/local_cache.rb:162:in `write_entry'
    from vendor/bundle/ruby/2.6.0/gems/dalli-2.7.9/lib/active_support/cache/dalli_store.rb:145:in `block (2 levels) in write'
    from vendor/bundle/ruby/2.6.0/gems/dalli-2.7.9/lib/dalli/client.rb:266:in `with'
    from vendor/bundle/ruby/2.6.0/gems/dalli-2.7.9/lib/active_support/cache/dalli_store.rb:83:in `with'
    from vendor/bundle/ruby/2.6.0/gems/dalli-2.7.9/lib/active_support/cache/dalli_store.rb:143:in `block in write'
    from vendor/bundle/ruby/2.6.0/gems/dalli-2.7.9/lib/active_support/cache/dalli_store.rb:386:in `block in instrument_with_log'
    from vendor/bundle/ruby/2.6.0/gems/dalli-2.7.9/lib/active_support/cache/dalli_store.rb:395:in `block in instrument'
    from vendor/bundle/ruby/2.6.0/bundler/gems/rails-9f39d00ed29f/activesupport/lib/active_support/notifications.rb:205:in `instrument'
    from vendor/bundle/ruby/2.6.0/gems/dalli-2.7.9/lib/active_support/cache/dalli_store.rb:394:in `instrument'
    from vendor/bundle/ruby/2.6.0/gems/dalli-2.7.9/lib/active_support/cache/dalli_store.rb:386:in `instrument_with_log'
    from vendor/bundle/ruby/2.6.0/gems/dalli-2.7.9/lib/active_support/cache/dalli_store.rb:142:in `write'
    from vendor/bundle/ruby/2.6.0/gems/dalli-2.7.9/lib/active_support/cache/dalli_store.rb:116:in `fetch'
```

**Comment by alexisraca** [comment]
Having the same problem with rails 6.1.3

**Comment by alexisraca** [comment]
The problem got fixed. Thank you!

**Comment by alexisraca** [comment]
For anyone having this problem:

- we changed to mem_cache_store which solved the bug
- Then we found another bug about "undefined method get_multi_cas"

If you are using identity_cache on the latest tag, there is a bugfix in this commit https://github.com/mperham/connection_pool/commit/97b269879f90ca0919a605eafb59c96ed1c8bea0 right above the top tag.

it is related to the connection_pool configuration.

**Comment by ghiculescu** [comment]
We had this issue happen after switching to the `mem_cache_store` if the value `false` was cached anywhere. For now we are rolling cache keys where this is likely, but have also proposed a fix in Rails: https://github.com/rails/rails/pull/42559

**Comment by zhengpd** [comment]
> undefined method `dup_value!' with dalli 2.7.11 and rails 6.1

Saw this when using `:dalli_store`. After switched to `:mem_cache_store` the error is gone.

**Comment by alexisraca** [comment]
@petergoldstein Everything is cool now. The fixes posted in my last comment solved everything. There was a bug in our implementation with `identity_cache` which was solved by a commit above the top tag.

**Comment by petergoldstein** [comment]
Thanks @alexisraca .

Closing this issue.
