### ISSUE TITLE
[bug] Dalli 2.x multi get key encoding issue when key length is over 250 chars

### ISSUE THREAD

**Issue by sbeckeriv** [petergoldstein/dalli#773]
Dearest Maintainer,

I dont know if you are taking issues for dalli 2.x but I searched and could not find any issue listed. I am running Rails 5.2. In dev I have no namespace configured. In staging/prod I do have a namespace configured. I started using Rails mulit get caches for collection templates. It worked well in dev but not in staging/prod. 

The issue is that my keys are over 250chars long and the muliget is double encoding the key once with the namespace and once without. 

[edit]
Our solution was to Digest::SHA256.hexdigest our keys and configure namespaces in dev.

It starts here 
https://github.com/petergoldstein/dalli/blob/2.x/lib/active_support/cache/dalli_store.rb#L180
namespace key truncates the key
https://github.com/petergoldstein/dalli/blob/f82b9e131fec0b5c3ee341e7c89d7737f67c20a7/lib/active_support/cache/dalli_store.rb#L348

example: (key 1)
views/path/_file:ec089b2e5c930db5405842e2cad58ce8/9401a5240e8b9f25dd611430ec0ab41081c15ccc0e15513bd9afa95465b9b119/9401a5240e8b9f25dd611430ec0ab41081c15ccc0e15513bd9afa95465b9b1:md5:ffb201840c2122fbf2e5583b5e8d4711

then we get to the yeilder and groups for keysL
https://github.com/petergoldstein/dalli/blob/f82b9e131fec0b5c3ee341e7c89d7737f67c20a7/lib/dalli/client.rb#L427

groups for keys calls mapped_keys
https://github.com/petergoldstein/dalli/blob/f82b9e131fec0b5c3ee341e7c89d7737f67c20a7/lib/dalli/client.rb#L298

which calls validate_key
https://github.com/petergoldstein/dalli/blob/f82b9e131fec0b5c3ee341e7c89d7737f67c20a7/lib/dalli/client.rb#L380

this calls key_with_namespace(key) which adds my namespace in prod/staging but not dev. because my key is already at 250..

key 2 (I didnt get the real string here)
namespace-views/path/_file:ec089b2e5c930db5405842e2cad58ce8/9401a5240e8b9f25dd611430ec0ab41081c15ccc0e15513bd9afa95465b9b119/9401a5240e8b9f25dd611430ec0ab41081c15ccc0e15513bd9afa95465b9b1:md5:ffb201840c2122fbf2e5583b5e8d4711

it runs that logic again and re-hashes. I didnt get this key. so now the mapping https://github.com/petergoldstein/dalli/blob/f82b9e131fec0b5c3ee341e7c89d7737f67c20a7/lib/active_support/cache/dalli_store.rb#L180
has key 1.  but the mulit fetch is fetching  key2 and returning key2 without the namespace. so when read_mult looks at the results the hash keys do not match any more.

the worst part of this for the rails collection caching partial fetching is that it is rewriting the key1 always as a miss.

Like i said I am unsure if you are patching 2.x and I understand if you close this issue. I hope that it might save someone else some debugging time. 

Thanks again for the amazing work!

Becker

**Comment by petergoldstein** [comment]
@sbeckeriv Sorry for the slow response.  In Dalli 3.x we've eliminated DalliStore in favor of the MemCacheStore that's included in Rails.  Do you see the same issue when using that store?

**Comment by sbeckeriv** [comment]
Hey peter,

I am no longer work on that project. I didnt get to try it with 3.x because our fix was to hash our long keys. Thanks for reply. I am going to close as 2.x branch will not be updated. Hopefully the wall of text might help prevent someone from having a deep dive as well.

Thanks again for your hard work on this project.
Becker
