### ISSUE TITLE
Question issue upgrade 3.0.1

### ISSUE THREAD

**Issue by ips219** [petergoldstein/dalli#794]
After 3.0.1 migration of today we have a problem in the start-up of redmine

`SyntaxError: /usr/local/bundle/gems/dalli-3.0.1/lib/dalli/client.rb:369: syntax error, unexpected keyword_rescue, expecting keyword_end
      rescue DalliError, NetworkError => e
            ^
/usr/local/bundle/gems/dalli-3.0.1/lib/dalli/client.rb:369: dynamic constant assignment
      rescue DalliError, NetworkError => e
                        ^
/usr/local/bundle/gems/dalli-3.0.1/lib/dalli/client.rb:369: dynamic constant assignment
ue DalliError, NetworkError => e
                              ^
/usr/local/bundle/gems/dalli-3.0.1/lib/dalli/client.rb:369: syntax error, unexpected =>, expecting '='
ue DalliError, NetworkError => e
`
Is it an expected version migration issue or a regression not expected of last commit?

Thanks and best regards!

**Comment by ips219** [comment]
In my case it is Redmine running over a Docker Linux container.... As @zumodevidrio  commented in [dmsf](danmunn/redmine_dmsf#1297) fixing the plugin dependency to an older version resolved the issue in redmine.

**Comment by zumodevidrio** [comment]
Same environment for me, Redmine over Docker Linux and Ruby version 2.4.6p354

**Comment by petergoldstein** [comment]
As these issues have either been clarified (minimum Ruby version) or addressed (Windows compatibility) with the 3.0.2 release, I'm going to close this issue.
