### ISSUE TITLE
Confirm threadsafe behavior in Rack session adapter

### ISSUE THREAD

**Issue by petergoldstein** [petergoldstein/dalli#829]
https://github.com/petergoldstein/dalli/blob/708b32a355917fa3b8a2d44ea9e78ecd4c012264/lib/rack/session/dalli.rb#L147

About one year ago the Rack session adapter was deleted and then restored.  In the process, the threadsafe value for pool configurations was changed from `false` to `true`.  This seems off, as this looks like the only circumstance in which we'd want to disable thread-level locking - we have a connection pool that manages access to the underlying client.

This issue tracks the need to determine whether this change was intentional and appropriate given the client semantics.

@mperham - what's your take on this change?  Was it deliberate, or an artifact of the deletion and restoration.

**Comment by mperham** [comment]
When used in a pool, there’s no point in adding a Mutex. We should be advising people to use Dalli in a pool setup and deprecating the use of a global shared connection.

**Comment by petergoldstein** [comment]
@mperham Right.  Which is why I'm confused why you changed this to set the threadsafe value to true.  Since it uses a pool inside the Session adapter I think we can just set it to false in this case.  This basically restores the old behavior.

**Comment by mperham** [comment]
I didn’t realize I had made that change. I don’t recall why I did this, did
I merge a PR from someone else?

**Comment by petergoldstein** [comment]
@mperham It doesn't look like it.  Change came in during this commit - https://github.com/petergoldstein/dalli/commit/7be38027f36cfd5e3e8dd9fe0d2d5843bf7292da#diff-5b0daa41888b310e1f62ed8e25176bfe8b57ef3767dd7602a8be99c5c8ff88dd

**Comment by mperham** [comment]
Looks like it was just a mistake on my part.

**Comment by petergoldstein** [comment]
@mperham Great.  Thanks for clarifying.  I'll change that in my PR to switch over to use Abstract::PersistedSecure
