### ISSUE TITLE
Example of Dalli::Client.set with ttl or expiry time

### ISSUE THREAD

**Issue by ndvbd** [petergoldstein/dalli#897]
How do I set an entry that I want to last (cached) for a certain amount of time, for example 1 hour?

**Comment by petergoldstein** [comment]
@ndvbd You can either set the TTL on a global level (by using the `expires_in` option on the client - https://github.com/petergoldstein/dalli/wiki/Dalli::Client-Options ) or pass an explicit `ttl` argument to the `set`/`add`/`replace`/`set_cas`/`add_cas` method you invoke to set the value.

Does that clear it up?

**Comment by ndvbd** [comment]
Yes thanks
