### ISSUE TITLE
Add error_handler option as Proc to Dalli::Store

### ISSUE THREAD

**Issue by johnnyshields** [petergoldstein/dalli#907]
Currently Dalli::Store supports a `raise_errors` (true/false) config.

I'd like more fine grained error handling like Rail's Redis Store supports. Would propose to add `error_handler` option as a proc, which is what Redis does.

My main reason for this is related to: https://github.com/rack/rack-attack/pull/577

**Comment by petergoldstein** [comment]
@johnnyshields `Dalli::Store` is no longer supported.  It was deprecated in the 2.7.x versions and removed with 3.0.x.  

You can find the MemCacheStore class here - https://github.com/rails/rails/blob/main/activesupport/lib/active_support/cache/mem_cache_store.rb

**Comment by johnnyshields** [comment]
Thanks, will close issue!
