### ISSUE TITLE
Get expiry time for key?

### ISSUE THREAD

**Issue by mecampbellsoup** [petergoldstein/dalli#916]
I am using the following ~hack~ code 😉 to get a dump of all keys from our memcached server via telnet:

```ruby
      keys = []
      memcached =
        Net::Telnet.new('Host' => 'memcached', 'Port' => 11_211, 'Timeout' => 3)

      matches =
        memcached
          .cmd('String' => 'stats items', 'Match' => /^END/)
          .scan(/STAT items:(\d+):number (\d+)/)

      slabs =
        matches.inject([]) do |items, item|
          items << Hash[*%w[id items].zip(item).flatten]
          items
        end

      slabs.each do |slab|
        memcached.cmd(
          'String' => "stats cachedump #{slab['id']} #{slab['items']}",
          'Match' => /^END/
        ) do |c|
          c.scan(/^ITEM (.+?) \[(\d+) b; (\d+) s\]$/).each do |key_data|
            keys << key_data[0]
          end
        end
      end

      slabs.each do |slab|
        memcached.cmd(
          'String' => "stats cachedump #{slab['id']} #{slab['items']}",
          'Match' => /^END/
        ) do |c|
          c
            .scan(/^ITEM (.+?) \[(\d+) b; (\d+) s\]$/)
            .each do |key_data|
            cache_key, bytes, expires_time = key_data
            rows_hash[cache_key] = [
              slab['id'],
              Time.at(expires_time.to_i),
              bytes
            ]
          end
        end
      end
```
You can see that using `stats cachedump` I also get the TTL _for the key_. However, this doesn't seem to be exposed/included in what `Dalli::Client.get` returns.

Is there a way to get the expiry for a key using this client?

Use case: after/while looking up a user's session in memcached, I'd like to confirm the cache data hasn't expired. Previously we used JWTs and had code like this:

```ruby
  def decoded_token
    algorithm = 'RS256'
    public_key_path = ENV['JWT_PUB_KEY_PATH']
    public_key_contents = File.read(public_key_path)
    public_key = OpenSSL::PKey::RSA.new(public_key_contents)
    @decoded_token ||=
      JWT.decode(http_token, public_key, true, { algorithm: algorithm })
  end
```
`JWT.decode` would validate the `exp` key in the token was not in the past, thus enforcing JWT TTL.

I suppose this concern is more relevant for JWTs since they're issued once and only once and thus they should have as short an expiry as possible for one's application. In contrast, if using server-side session caching via memcached (what I'm migrating to now), the cache key's TTL seems to be updated on each `get` operation for that key.

Sorry this ended up turning into a bit of a ramble but - do you have any thoughts? Thanks! 😄

**Comment by petergoldstein** [comment]
So there's not really a way to do what's being asked (getting the current expiry time for a key).  But I don't really understand the point.  This sentence:

`after/while looking up a user's session in memcached, I'd like to confirm the cache data hasn't expired.`

seems to be based on a misunderstanding of how this all works.  Specifically:

1. If you lookup a key, and get a result, by definition the key hasn't expired. 
2. If you want to check if a previously requested key is still in cache, just issue another `get` for that key.  Then see #1.

A JWT is an entirely different thing than a cache.  The workflow as described above has no relevance for a server-side session caching model.  The JWT is a client side token that can be accessed after expiration.  A server side session is either in cache or is not.

**Comment by mecampbellsoup** [comment]
Right, I agree with you - I was just thrown off by memcached reporting expiry times for keys, e.g.:

```
irb(main):024:0> puts row_format % headings
|      id |                      expires |        bytes | cache_key                                |
=> nil
irb(main):025:0> rows.each { |row| puts row_format % row }
|       2 |    2022-06-12 23:18:53 +0000 |           17 | memc.sess.key.1ncssss2kjafmeb4g1g8uf92ve |
|       2 |    2022-06-12 23:18:36 +0000 |           18 | memc.sess.key.hlqr48serdqoccohdccoo6ikla |
|       2 |    2022-06-12 23:18:05 +0000 |           18 | memc.sess.key.hfgg2q1e403jb1iu9vvpcksl3s |
|       2 |    2022-06-12 23:18:00 +0000 |           18 | memc.sess.key.n2j0jth9cqq0ui5om0t6fi4l1m |
|       2 |    2022-06-12 23:17:53 +0000 |           17 | memc.sess.key.dtl1f8p3149v6f2pjhoehjstl4 |
|       2 |    2022-06-12 23:17:35 +0000 |           18 | memc.sess.key.1jf9sfhr53fopo1vllh9jjbnf2 |
|       2 |    2022-06-12 23:17:04 +0000 |           18 | memc.sess.key.n608hb36eqgdgrdu7chq9jvcjv |
|       2 |    2022-06-12 23:17:00 +0000 |           18 | memc.sess.key.nj6crlchvcfkms5ds39bqgf652 |
|       2 |    2022-06-12 23:16:53 +0000 |           17 | memc.sess.key.vthkcmfplopq942lu0euhjrem2 |
|       2 |    2022-06-12 23:16:34 +0000 |           18 | memc.sess.key.sp1l0lcpc5eo8nlmd61sgjma1h |
|       2 |    2022-06-12 23:16:04 +0000 |           18 | memc.sess.key.hg1apubj11uj7btucvb0eebc5m |
|       2 |    2022-06-12 23:16:01 +0000 |           18 | memc.sess.key.7kione3lvrfdleqodrbjfsqogd |
|       2 |    2022-06-12 23:15:54 +0000 |           17 | memc.sess.key.1v5gjfm3h7u584b0i807k3ijsr |
```

But as you point out this is simply a different use case/purpose.

Memcached uses this "expiry" timestamp more like a TTL, but also I believe for prioritizing which entries should be cleared first in the case that e.g. storage capacity is reached and it has to start making decisions about what to evict first. See https://github.com/memcached/memcached/wiki/UserInternals#when-are-items-evicted.

In any case, you're right that I don't need to check it since it's the server's job to make sure the cache data is removed when expiry is reached, not the client's job to double check that.

**Comment by petergoldstein** [comment]
Closing.

**Comment by raivil** [comment]
Hey @petergoldstein,
First of all, thank you for maintaining the gem. 
Let's say, on a hypothetical situation,  that I need to visualize when a key will expire so I can decide whether or not to take action (expire ahead of time, for instance). 
What would be a way to retrieve it for a specific key (or for a set of key)?
I'm not a memcached expert at all, but I've found that it can be retrieved with the `mg key t` command as shown below but I could't find support for it on the gem.
```
mg key_name t
HD t3575
```

Are there plans to support `meta get` commands on the client?
Would you recommend another approach?

Thank you.

**Comment by petergoldstein** [comment]
@raivil So let me clarify some confusion about memcached first, and then we can discuss the use case.

`meta` is a communication protocol, like `binary`.   `Dalli` has support for use of both the `binary` (by default) and `meta` protocols.  See the docs for details.  Using `meta` or `binary` is a memcached connection level decision (or from the `Dalli` perspective a client level decision) and you can't switch between them on a single connection or client.  So the command being presented is just the `get` command, using the `meta` protocol, with a TTL flag.

`Dalli` doesn't support the TTL flag on `get`, and is unlikely to do so in the near future.  The `Dalli` get command is designed to have a simple return type - namely the data that's cached under that key - and has no way of returning the TTL (or any of the other meta attributes that you could retrieve) without modifying the signature.

That all said, the use case being presented really doesn't seem to match up with using memcached in its standard use case - as a cache.  It almost sounds like you're trying to use memcached as a database, which is not generally recommended.  In a cache you generally:

1. Set key/value data (optionally with a TTL)
2. Retrieve the data by key, being robust against a cache miss.  TTL may be updated on gets for data that's being used (`get and touch`)
3. Generally allow the cache to manage deletion of data via TTL or cache space limitations.  You may occasionally flush the server, but it's rare to clean up particular sets of keys.
4. Data modifications are limited, with some special operations to support metrics tracking type use cases (increment/decrement) and TTL extension (keeping data around even if it hasn't been used recently)

Why is it necessary to "visualize when a key will expire" under this use case?  If the key is known, and the TTL may not be what is desired, `touch` can be used to set the TTL for that key.  There's no reason to actually get either the data or the current TTL.

And if it's necessary to reduce the TTLs of your existing data, I'd suggest one of the following may be true:

1. TTLs are being set too long on `set` or `gat`.  In this case, just reduce the TTLs, and `gat` can be used to ensure that frequently used keys are refreshed.
2. The key strategy doesn't match your use case - keys are being reused for different data when they shouldn't be.  Proper structuring of keys (see Rails caching for examples) can avoid unnecessary key reuse
