### ISSUE TITLE
Question: Session cookies with Dalli

### ISSUE THREAD

**Issue by leehsueh** [petergoldstein/dalli#931]
Hi there,

I have general questions around the relationship between Dalli as a memcached client and how session id's are set in cookies. This started as I was looking for way to configure that cookies with the session id are marked as "secure" in the Set-Cookie header. Is it possible to do that with one of the options?

Thanks for your help/guidance!

**Comment by petergoldstein** [comment]
@leehsueh Dalli as a gem does not include a bundled session store.  Details on how to use memcached/Dalli as the backend for a session store (in Rails specifically, which includes such a store) can be found here - https://github.com/petergoldstein/dalli/wiki/Using-Dalli-with-Rails
