### ISSUE TITLE
DalliError: Response error 6: Incr/decr on a non-numeric value

### ISSUE THREAD

**Issue by ParthivSavani4582** [petergoldstein/dalli#955]
Currently experiencing **DalliError: Response error 6: Incr/decr on a non-numeric value** error in the application.

![Screenshot from 2023-03-03 15-08-47](https://user-images.githubusercontent.com/106149921/222686345-d4824d80-1205-4b8a-9578-51aee2de127f.png)

Rails v - 3.2.18
Ruby - ruby-2.3.3
dalli - 2.7.2

**Comment by petergoldstein** [comment]
@ParthivSavani4582 I'm not sure what you're passing in to the incr/decr.  Have you confirmed that it's actually a numeric value?

I need a lot more context here.  Thanks!

**Comment by jamiemccarthy** [comment]
@ParthivSavani4582 I'm going to close this issue out. If you can confirm you got this error and the value was actually numeric, please open a new issue with more details. Thank you!
