### ISSUE TITLE
connection_pool gem is required

### ISSUE THREAD

**Issue by matthewhively** [petergoldstein/dalli#976]
I'm testing out Dalli3 and the wiki documentation is confusing and unclear.

In many sections of the wiki it says connection_pool gem is recommended for thread safe operations.
see:
- https://github.com/petergoldstein/dalli/wiki/Using-Dalli-with-Rails
- https://github.com/petergoldstein/dalli/wiki/Thread-Safety

However when I attempt to run our rails app with dalli3 it throws an error:
`ruby-2.7.8/gems/dalli-3.2.6/lib/rack/session/dalli.rb:5:require 'connection_pool'`
`require: cannot load such file -- connection_pool (LoadError)`
Which suggests that connection_pool is non optional.

But then the Gemfile lists `connection_pool` under development dependencies only, so it is not installed by default.

----

While I certainly can add connection_pool to our gemfile, this seems very inconsistent. I don't like the idea of following documentation that is not accurate.
It also seems possibly un-necessary to use a connection_pool as we are using unicorn which doesn't use threads, so a pool should be un-necessary.

**Comment by boutil** [comment]
Hi,
I was about to file the same report, triggered by a bug reported in Debian:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1033310
(the dependency was not automatically added, because not explicitly listed in the gemspec file)

**Comment by petergoldstein** [comment]
The simple answer to this is that the `Dalli::Client` and related files in the `Dalli` namespace do not require `connection_pool`, while using `Rack::Session::Dalli` does.  It is possible (and common) to use `Dalli` without using the latter, which is why `connection_pool` is a dev dependency and not a dependency.

I agree that the wiki could be clearer on this point.  Modifications to the documentation are welcome.  There's a minor note in the CHANGELOG, but that's not particularly easy to find.

**Comment by matthewhively** [comment]
It would be ideal if there were some way to have the gem intelligently add connection pool to its dependencies if it is running as part of a railsapp. But since that is probably not possible...
Perhaps the repo README file should have a section prominently indicating that when used as part of a rails/rack app connection_pool gem must also be required.
An alternative would be to build 2 gems for each version: `dalli` and `dalli_rails`/`dalli_rack` with the only difference being the gemspec

**Comment by petergoldstein** [comment]
@matthewhively I'm not entirely sure why the `lib/rack/session/dalli` class would be loaded by a Rails app unless it's specifically configured to use the Dalli Rack session manager.  It may be that Zeitwerk is pulling all of that in, but that's not the behavior I would expect.  Have you configured your app to use this session manager?

**Comment by matthewhively** [comment]
@petergoldstein 
Our railsapp (rails 5.2.8.1) is configured to use the `mem_cache_store`, as recommended, for both cache_store and session_store
Relevant lines:
```
memcache_options = {
    namespace:  "cache-#{Rails.env}",
    compress:   true,
    expires_in: 1.day
  }
config.cache_store = :mem_cache_store, memcache_servers, memcache_options
```
and
```
memcache_session_options = {
  memcache_server: Settings.memcache_servers,
  namespace:       "sess-m-#{Rails.env}",
 #compress:        true,
  expire_after:    7.days
}
Rails.application.config.session_store(:mem_cache_store, **memcache_session_options)
```

Would anything else from our config be helpful?

**Comment by petergoldstein** [comment]
I've updated the docs for the session store to make it clear that the `connection_pool` gem is required in that case.

**Comment by matthewhively** [comment]
> Rails 5.2.8 is pretty far back (already EOLd)

Yeah... tell me about it. *sigh*

**Comment by matthewhively** [comment]
Thanks for the wiki update.
Seems clear enough now.

**Comment by petergoldstein** [comment]
@boutil Do you need any further information?
