### ISSUE TITLE
Should I react to the "Fork detected, re-connecting child process" exception?

### ISSUE THREAD

**Issue by KIVagant** [petergoldstein/dalli#997]
Hi. 

I have a monitoring tool set up for an application that uses `dalli-2.7.11`.  I noticed that it generates significant amount of errors:

```
Dalli::NetworkError: Fork detected, re-connecting child process...
/usr/local/bundle/gems/dalli-2.7.11/lib/dalli/server.rb:219:in `reconnect!': Fork detected, re-connecting child process... (Dalli::NetworkError)
```

The error is coming [from this logic](https://github.com/petergoldstein/dalli/blob/67942b8db6ba8ae9c39e30d9c0c63fb1525586b3/lib/dalli/protocol/connection_manager.rb#L232), as I understand. My assumption, this is related to the `WEB_CONCURRENCY` setting for Unicorn. And each fork triggers this error. Is it really an error or more like a warning? If it is not a problem, but an expected behavior, can the message be suppressed? Should I be worried about it? Is there a case when the error is a clue to some bigger problem? The app produces hundreds of thousands logs like this.

Thank you.

**Comment by petergoldstein** [comment]
Happy to let the community response if they have any insight, but this isn't an issue that I'll be looking at as a maintainer.  

2.7.11 is four years old at this point, this issue is largely a result of the forking strategy in Unicorn, and there is no actual error use case provided - it's basically ambiguous logs.

If you'd like to suppress the error message you can presumably do so either in your logging framework via regexp or by creating a fork of 2.7.11

**Comment by KIVagant** [comment]
Hi Peter. Yeah, I agree that this is not directly related to Dalli, but I'm more seeking for an advice since I'm far from being expert in this area. 

The Dalli version I mentioned may confuse, because the error line and the logic is still there in the `main` branch and, I believe, there was no big changes since that version till this day. 
- https://github.com/petergoldstein/dalli/blob/main/lib/dalli/protocol/connection_manager.rb#L223

Correct me if I'm wrong, but I assume your response can be read as "this is not an actual application error even though it is an exception and causes a reconnect/soft restart".

I am okay to filter out some logs, I have some instruments for that.

**Comment by petergoldstein** [comment]
@KIVagant So there are cases where this might be considered an application error.  In your case, assuming the error is a result of normal Unicorn forking, I think your reading is correct.

**Comment by KIVagant** [comment]
Thank you!
